### ISSUE TITLE
Equal values are interpreted differently due terraform import & plan

### ISSUE THREAD

**Issue by g-nikolay** [hashicorp/terraform-provider-google#10428]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.9
on linux_amd64
provider registry.terraform.io/hashicorp/google v3.90.0

### Affected Resource(s)

* google_compute_instance
* google_compute_disk

### Deployment Manager Configuration Files
``` yaml
resources:
- type: gcp-types/compute-v1:instances
  name: instance-test
  properties:
    zone: us-central1-f
    machineType: zones/us-central1-f/machineTypes/f1-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: projects/debian-cloud/global/images/family/debian-10
        diskName: disk-test
    - deviceName: extra-disk-test
      boot: false
      autoDelete: true
      source: $(ref.compute-disk-test.selfLink)
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/{PROJECT_ID}/global/networks/default
- name: compute-disk-test
  type: gcp-types/compute-v1:disks
  properties:
    description: a sample encrypted, blank disk
    physicalBlockSizeBytes: 4096
    sizeGb: 1
    type: projects/{PROJECT_ID}/zones/us-central1-f/diskTypes/pd-ssd
    zone: us-central1-f
```

### Terraform Configuration Files

```tf
resource "google_compute_instance" "instance_test" {
  name = "instance-test"
  machine_type = "zones/us-central1-f/machineTypes/f1-micro"
  zone = "us-central1-f"
  boot_disk {
    device_name = "boot"
    auto_delete = true
    initialize_params {
      image = "projects/debian-cloud/global/images/family/debian-10"
    }
  }
  attached_disk {
    device_name = "extra-disk-test"
    source = google_compute_disk.compute_disk_test.id
  }
  network_interface {
    network = "https://www.googleapis.com/compute/v1/projects/{PROJECT_ID}/global/networks/default"
  }
}

resource "google_compute_disk" "compute_disk_test" {
  name = "compute-disk-test"
  description = "a sample encrypted, blank disk"
  size = 1
  zone = "us-central1-f"
  type = "projects/{PROJECT_ID}/zones/us-central1-f/diskTypes/pd-ssd"
  physical_block_size_bytes = 4096
}
```

### Debug Output

[terraform plan output](https://gist.github.com/g-nikolay/4ab2602e9eaf8f22e8e0d65f280eb004)

### Expected Behavior
terraform import and apply commands run without any issue

### Actual Behavior
**Compute Disk**
* **type** field output after DM deploy is -> pd-ssd
* **type** field output after terraform import is -> projects/{PROJECT_ID}/zones/us-central1-f/diskTypes/pd-ssd
Technically values are equal, but this diff forces replacement.

Everything works as expected if I replace 
```tf
type = "projects/{PROJECT_ID}/zones/us-central1-f/diskTypes/pd-ssd"
```
with
```tf
type = "pd-ssd"
```

**Compute Instance**
* **machine_type** field output after DM deploy is -> f1-micro
* **machine_type** field output after terraform import is -> zones/us-central1-f/machineTypes/f1-micro
The same story. Nonetheless plan does not show replacement, apply command is failing with the message below
```
│ Error: Changing the machine_type, min_cpu_platform, service_account, enable_display, shielded_instance_config, scheduling.node_affinities or network_interface.[#d].(network/subnetwork/subnetwork_project) or advanced_machine_features on a started instance requires stopping it. To acknowledge this, please set allow_stopping_for_update = true in your config. You can also stop it by setting desired_status = "TERMINATED", but the instance will not be restarted after the update.
│
│   with google_compute_instance.instance_test,
│   on main.tf line 1, in resource "google_compute_instance" "instance_test":
│    1: resource "google_compute_instance" "instance_test" {
│
```

### Steps to Reproduce

1. `gcloud deployment-manager deployments create disk-test --config config.yaml`
2. `terraform import google_compute_instance.instance_test {PROJECT_ID}/us-central1-f/instance-test`
3. `terraform import google_compute_disk.compute_disk_test {PROJECT_ID}/us-central1-f/compute-disk-test`
4. `terraform plan`

### References

* #0000

b/304967923
