### ISSUE TITLE
google_bigquery_table import is failing without any meaningful error

### ISSUE THREAD

**Issue by g-nikolay** [hashicorp/terraform-provider-google#10471]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.9
on linux_amd64
provider registry.terraform.io/hashicorp/google v3.90.0

### Affected Resource(s)

* google_bigquery_table

### Terraform Configuration Files

```tf
resource "google_bigquery_dataset" "dataset_gcp_res_import_test" {
  labels = {
    from = "my-test"
  }
  description = "my test"
  default_table_expiration_ms = 7200000
  location = "us-west1"
  dataset_id = "dataset_gcp_import_test"
}

resource "google_bigquery_table" "table_gcp_res_import_test" {
  dataset_id = google_bigquery_dataset.dataset_gcp_res_import_test.dataset_id
  table_id = "table_gcp_import_test"
}
```

### Debug Output

[gist](https://gist.github.com/g-nikolay/5060775b475b8e4d3b7cfe98bddca4c9)

### Actual Behavior

terraform is failing with the following message
```
│ Error: 1 error occurred:
│       * ForceNew: No changes for schema
│
│
│
│   with google_bigquery_table.table_gcp_res_import_test,
│   on main.tf line 11, in resource "google_bigquery_table" "table_gcp_res_import_test":
│   11: resource "google_bigquery_table" "table_gcp_res_import_test" {
│
```

### Steps to Reproduce

1. Create GCP bq and table
2. Import created resources using attached config
3. `terraform import`
4. `terraform plan`

### References

* #0000

**Comment by edwardmedia** [comment]
@g-nikolay what config and command did you use? 

> Import created resources using attached config

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_table#import

**Comment by g-nikolay** [comment]
@edwardmedia basically I had 2 options - 1 manually created resources, 2 using dm config below:
```yaml
resources:
- type: gcp-types/bigquery-v2:datasets
  name: dataset-gcp-res-import-test
  properties:
    labels:
      from: my-test
    defaultTableExpirationMs: 7200000
    location: us-west1
    description: 'my test'
    datasetReference:
      datasetId: dataset_gcp_import_test
- type: gcp-types/bigquery-v2:tables
  name: table-gcp-res-import-test
  properties:
    datasetId: $(ref.dataset-gcp-res-import-test.datasetReference.datasetId)
    tableReference:
      tableId: table_gcp_import_test
```
