### ISSUE TITLE
EventArc trigger matching_criteria does not support 'operator' field

### ISSUE THREAD

**Issue by hile-codento** [hashicorp/terraform-provider-google#11312]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

EventArc eventFilters resource can be configured with matching_criteria field in terraform. This terraform schema supports fields 'attribute' and 'value' only.

Third field 'operator' is also required. This field can be used to implement additional resource filtering, at least with matching path patterns.

### New or Affected Resource(s)

* google_eventarc_trigger

Example configuration for the 'operator' field can be defined from cloud console by selecting resource type 'path pattern' in the eventarc trigger 'edit' form. 

For a cloud storage bucket the resulting configuration is something like following, as seen in `gcloud eventarc triggers describe` output after defining pathPattern in web console:

```
eventFilters:
- attribute: resourceName
  operator: match-path-pattern
  value: /projects/_/buckets/my-bucket-name/objects/*
- attribute: type
  value: google.cloud.audit.log.v1.written
- attribute: serviceName
  value: storage.googleapis.com
- attribute: methodName
  value: storage.objects.create
 ```
 
### Potential Terraform Configuration

```tf
    matching_criteria {
      attribute = "resourceName"
      operator = "match-path-pattern"
      value = "projects/_/buckets/${var.my_bucket_name}/objects/*"
    }
```

### References

b/272800934
