### ISSUE TITLE
Allow `google_tags_tag_binding` resource to accept a namespacedName for the `tag_value` argument

### ISSUE THREAD

**Issue by nphilbrook** [hashicorp/terraform-provider-google#11367]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The `google_tags_tag_binding` resource _only_ accepts the `name` for the `tag_value` argument, which is in the format `tagValues/12345` - e.g. there is nothing in this value that is readable or contains the tag value's descriptive shortname.

Via the GCP API you can use either the `name` OR the `namespacedName` when creating a tag binding - the namespaced name is in the format `<org_id>/<key short name>/<value short name>` and is much more descriptive/readable.

In our initial rollout of GCP IAM tags we are struggling with writing readable configuration using `tagValues/XXXX` format. For example, we have a module for which we want to accept a tag value so that we can tag the created resources using this value. But passing in `tagValues/XXXX` doesn't denote anything descriptive about what the tag value actually is, and even finding the correct value to use is problematic. We considered storing our own copy of namespacedName -> name mappings (which we may still do if this request is rejected). But this seems pretty silly given that you can do this with gcloud:
```
@arlo ~ $ gcloud alpha resource-manager tags bindings create --tag-value=345678/foo/bar --parent=//cloudresourcemanager.googleapis.com/folders/12345
done: true
response:
  '@type': type.googleapis.com/google.cloud.resourcemanager.v3.TagBinding
  name: tagBindings/%2F%2Fcloudresourcemanager.googleapis.com%2Ffolders%2F12345/tagValues/67890
  parent: //cloudresourcemanager.googleapis.com/folders/12345
  tagValue: tagValues/67890
```
Notably there is also a lack of any data resources so we can't look up the `name` of a tagValue given the `namespacedName`.

### New or Affected Resource(s)

* google_tags_tag_binding

### Potential Terraform Configuration

```tf
resource "google_tags_tag_binding" "bar_binding" {
  parent    = "//cloudresourcemanager.googleapis.com/folders/12345"
  tag_value = "345678/tag_key_short_name_foo/tag_value_short_name_bar"
}

```
Where 12345 is the ID of a folder, 345678 is the ID of an organization, `tag_key_short_name_foo` is the shortName of a tag key, and `tag_value_short_name_bar` is the shortName of a tag value.

### References
I could not find any issues requesting this feature.

[GCP docs describing the gcloud call I demonstrated above](https://cloud.google.com/resource-manager/docs/tags/tags-creating-and-managing#attaching)
[terraform-provider-google docs describing only the `tagValues/XXXX` format being accepted](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/tags_tag_binding#tag_value)

N.b. I hope that myself or one of my teammates at Wayfair can contribute this feature in the near future, but as PRs need to reference an issue I am starting with this issue and appreciate any feedback on the feature request.
