### ISSUE TITLE
Missing support for loggingConfig in google_container_aws_cluster

### ISSUE THREAD

**Issue by Aracki** [hashicorp/terraform-provider-google#11679]
Here is the official [documenation](https://cloud.google.com/anthos/clusters/docs/multi-cloud/aws/how-to/cloud-logging#enable_workload_logging). By default `google_container_aws_cluster` will be created only with SYSTEM logs enabled:

```
loggingConfig:
  componentConfig:
    enableComponents:
    - SYSTEM_COMPONENTS
```

It should be configurable to enable "WORKLOAD" logs as well.

PS. Only gcloud alpha has the ability to set loggingConfig: https://cloud.google.com/sdk/gcloud/reference/alpha/container/aws/clusters/create#--logging
