### ISSUE TITLE
Support preconfigured_waf_config field on rules for google_compute_security_policy resource

### ISSUE THREAD

**Issue by davidalger** [hashicorp/terraform-provider-google#12735]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Cloud Armor added support for excluding certain request fields (headers, cookies, params, uris, etc) from inspection, and naturally we would like to configure these preconfigured WAF exclusions via the same Terraform resource that is creating the policy and associated rules.

These exclusions can be added and removed via `gcloud beta compute security-policies rules add-preconfig-waf-exclusion` and `gcloud beta compute security-policies rules remove-preconfig-waf-exclusion` and are configured on a per-policy-per-rule basis.

One might for example configure various exclusions for the XSS rules to avoid being tripped on a CMS system:

```shell
$ gcloud beta compute security-policies rules add-preconfig-waf-exclusion 1001 \
  --security-policy=my-waf-policy --project=my-project \
  --request-query-param-to-exclude=op=EQUALS,val=description \
  --request-query-param-to-exclude=op=EQUALS,val=notes \
  --target-rule-set=xss-v33-stable
```

```shell
$ gcloud beta compute security-policies rules describe 1001 \
  --security-policy=my-waf-policy --project=my-project \
```

```yaml
---
action: deny(403)
description: Cross-site scripting
kind: compute#securityPolicyRule
match:
  expr:
    expression: evaluatePreconfiguredWaf("xss-v33-stable", {"sensitivity":"3"})
preconfiguredWafConfig:
  exclusions:
  - requestCookiesToExclude:
    - op: EQUALS_ANY
    requestHeadersToExclude:
    - op: STARTS_WITH
      val: X-Prefix
    requestQueryParamsToExclude:
    - op: EQUALS
      val: description
    - op: EQUALS
      val: notes
    requestUrisToExclude:
    - op: STARTS_WITH
      val: /admin
    targetRuleSet: xss-v33-stable
  - requestQueryParamsToExclude:
    - op: EQUALS
      val: title
    targetRuleIds:
    - owasp-crs-v030301-id941350-xss
    targetRuleSet: xss-v33-stable
preview: true
priority: 1001
ruleNumber: '8'
```

### New or Affected Resource(s)

* google_compute_security_policy

### Potential Terraform Configuration

```tf
resource "google_compute_security_policy" "this" {
  name = "my-waf-policy"

  rule {
    action      = "deny(403)"
    priority    = "1001"
    description = "Cross-site scripting"
    preview     = true

    match {
      expr {
        expression = "evaluatePreconfiguredWaf(\"xss-v33-stable\", {\"sensitivity\":\"3\"})"
      }
    }

    preconfigured_waf_config {
      exclusion {
        request_header {
          operator = "STARTS_WITH"
          value    = "X-Prefix"
        }

        request_cookie {
          operator = "EQUALS_ANY" // value omitted when operator == EQUALS_ANY
        }

        request_uri {
          operator = "STARTS_WITH"
          value    = "/admin"
        }

        request_query_param {
          operator = "EQUALS"
          value    = "description"
        }

        request_query_param {
          operator = "EQUALS"
          value    = "notes"
        }

        target_rule_set = "xss-v33-stable"
      }

      exclusion {
        request_query_param {
          operator = "EQUALS"
          value    = "title"
        }

        target_rule_set = "xss-v33-stable"
        target_rule_ids = [ // optional list(string) to specifiy list of ids to target
          "owasp-crs-v030301-id941350-xss",
        ]
      }
    }
  }
}
```

### References

* https://cloud.google.com/armor/docs/rule-tuning?hl=en#exclude_request_fields_from_inspection
* https://cloud.google.com/compute/docs/reference/rest/beta/securityPolicies
* https://cloud.google.com/sdk/gcloud/reference/beta/compute/security-policies/rules/add-preconfig-waf-exclusion
* https://cloud.google.com/sdk/gcloud/reference/beta/compute/security-policies/rules/remove-preconfig-waf-exclusion
