### ISSUE TITLE
Cannot define interdependent environment variables with `google_cloud_run_service`

### ISSUE THREAD

**Issue by tomasgareau** [hashicorp/terraform-provider-google#12814]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.2.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.40.0
+ provider registry.terraform.io/hashicorp/google-beta v4.40.0
```

### Affected Resource(s)

* `google_cloud_run_service`

### Terraform Configuration Files

Take some example service where I'd like to interpolate some secret into another environment variable (e.g., for constructing a database URI given a secret username/password):

```tf
resource "google_cloud_run_service" "environment" {
  name     = "my-service"
  project  = "my-project-id"
  location = var.location

  autogenerate_revision_name = true

  template {
    spec {
      containers {
        image = "us.gcr.io/gcr-project/some-image:some-tag"

        dynamic "env" {
          for_each = { for idx, envvar in var.my_envvars : envvar.name => envvar.value }

          content {
            name  = env.key
            value = env.value
          }
        }

        env {
          name = "INTERPOLATED_VAR"
          value = "other var is: $(OTHER_VAR)"
        }

        env {
          name = "OTHER_VAR"
          value_from {
            secret_key_ref {
              name = "my-other-var-secret"
              key = "latest"
            }
          }
        }
      }
    }
  }
}
```

### Expected Behavior

The `google_cloud_run_service` documentation suggests that the `$(VAR_NAME)` syntax should allow me to interpolate environment variables in other environment variables. Emphasis mine:

> The env block supports:
> [name](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#name) - (Optional) Name of the environment variable.
> [value](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#value) - (Optional) **Variable references <span>$</span>(VAR_NAME) are expanded using the previous defined environment variables in the container** and any route environment variables. If a variable cannot be resolved, the reference in the input string will be unchanged. The <span>$</span>(VAR_NAME) syntax can be escaped with a double <span>$$</span>, ie: <span>$$</span>(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not. Defaults to "".

### Actual Behavior

The variable reference is _not_ expanded, and `INTERPOLATED_VAR` has the literal value `"other var is: $(OTHER_VAR)"`.

#### Interdependent environment variables are ordering sensitive

The [Kubernetes documentation on interdependent environment variables](https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/) mentions that

> When you create a Pod, you can set dependent environment variables for the containers that run in the Pod. To set dependent environment variables, you can use $(VAR_NAME) in the value of env in the configuration file.

The YAML for my Cloud Run service _does_ seem to have `INTERPOLATED_VAR` at the top:

```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  blah: blah
spec:
  template:
    metadata:
      annotations:
        blah: blah
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: my-sa@my-project.iam.gserviceaccount.com
      containers:
      - image: us.gcr.io/my-gcr-project/my-service-image:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: INTERPOLATED_VAR
          value: other var is: $(OTHER_VAR)
        - name: OTHER_VAR
          valueFrom:
          secretKeyRef:
            name: my-secret
            key: some-key
```

This may be why I'm not able to interpolate this value but AFAIK I have no way to control the order of the `env` blocks.

#### Dynamic env block

I've included a dynamic env block in the snippet above since I am using one -- I'm not sure if this would have an impact on the ordering of `env` blocks but thought I'd mention it in case it's pertinent.

### References

* This issue also touched on ordering sensitivity of `env` blocks in the `google_cloud_run_service`: https://github.com/hashicorp/terraform-provider-google/issues/9175
