### ISSUE TITLE
`google_compute_subnetwork` Network Self Link Attribute Reference

### ISSUE THREAD

**Issue by tgoodsell-tempus** [hashicorp/terraform-provider-google#13780]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The `google_compute_subnetwork` module supports passing one of the various types of formats for the "network" field, either just the name, the "ID" style, or the fully qualified API URL.

Pretty often, most resources / APIs like to use the `self_link` (fully qualified API URL) of the network and/or the subnetwork.

A nice to have on the subnetwork resource, where we're not also passing around the network object, would be a `network_self_link` field which is specifically coded to that value, instead of only the `network` field which returns the same format as passed in.

### Potential Terraform Configuration

```tf
resource "google_compute_subnetwork" "network-with-private-secondary-ip-ranges" {
  name          = "test-subnetwork"
  ip_cidr_range = "10.2.0.0/16"
  region        = "us-central1"
  network       = google_compute_network.custom-test.id
  secondary_ip_range {
    range_name    = "tf-test-secondary-range-update1"
    ip_cidr_range = "192.168.10.0/24"
  }
}

output "network_self_link" {
  value = google_compute_subnetwork.network-with-private-secondary-ip-ranges.network_self_link
}
```

### References

Based on GCloud Testing, this fully qualified value should always be in the API response, so this would just be a matter of setting this new attribute to that value:

```
creationTimestamp: '2023-02-16T13:25:49.007-08:00'
enableFlowLogs: true
fingerprint: redacted
gatewayAddress: 10.39.32.1
id: 'redacted'
ipCidrRange: 10.39.32.0/20
kind: compute#subnetwork
logConfig:
  aggregationInterval: INTERVAL_15_MIN
  enable: true
  filterExpr: 'true'
  flowSampling: 0.01
  metadata: INCLUDE_ALL_METADATA
name: gke-subnet
network: https://www.googleapis.com/compute/v1/projects/redacted/global/networks/redacted
privateIpGoogleAccess: true
privateIpv6GoogleAccess: DISABLE_GOOGLE_ACCESS
purpose: PRIVATE
region: https://www.googleapis.com/compute/v1/projects/redacted/regions/us-central1
secondaryIpRanges:
- ipCidrRange: 240.0.0.0/14
  rangeName: gke-pods
- ipCidrRange: 240.4.0.0/20
  rangeName: gke-services
selfLink: https://www.googleapis.com/compute/v1/projects/redacted/regions/us-central1/subnetworks/gke-subnet
stackType: IPV4_ONLY
```
