### ISSUE TITLE
Make unused async fields optional

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#14976]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment or [link](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) the pull request to this issue.

### Affected Resource(s)

* google_*

### Issue Description
We currently have a number of unused fields in our async block. A minimal block looks like this:

```yaml
async: !ruby/object:Api::OpAsync
 operation: !ruby/object:Api::OpAsync::Operation
   base_url: '{{op_id}}'
 # The following are all required but unused.
   path: 'unused'
   wait_ms: 0  # unused
 result: !ruby/object:Api::OpAsync::Result
   path: 'unused'
 status: !ruby/object:Api::OpAsync::Status
   path: 'unused'
   allowed: []
 error: !ruby/object:Api::OpAsync::Error
   path: 'unused'
   message: 'unused'
```

### References

* https://github.com/hashicorp/terraform-provider-google/issues/12431 and https://github.com/hashicorp/terraform-provider-google/issues/13337 cover use cases for some of the (currently unused) fields. However, for now we should just make them optional.
* b/288632787
