### ISSUE TITLE
Cloud SQL Edition setting does not persist

### ISSUE THREAD

**Issue by jawnsy** [hashicorp/terraform-provider-google#15553]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform 1.5.4 via Terraform Cloud

### Affected Resource(s)

* google_sql_database_instance (we are using the [latest release of sql-db, v16.0.0](https://github.com/terraform-google-modules/terraform-google-sql-db/releases/tag/v16.0.0))

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Expected Behavior

After manually setting the database edition to "ENTERPRISE" tier, we expected that it would be persisted in the state file.

### Actual Behavior

The database always shows an update is required in Terraform Cloud:

![image](https://github.com/hashicorp/terraform-provider-google/assets/52710/8dbb1797-f9d6-4682-8c49-1700b4388ebe)

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

b/298051076

**Comment by DanielRieske** [comment]
We recently added [database edition](https://github.com/GoogleCloudPlatform/magic-modules/pull/8602) to the providers schema, if you added this manually in GCP it's not within the Terraform state.

You can either import or ignore the field to solve this issue.

**Comment by jawnsy** [comment]
@DanielRieske Thanks for the quick response! Sorry, I think my bug report was a little unclear.

We modified our Terraform file (we're using the sql-db module) to add `edition = "ENTERPRISE"`, applied the change, and we expected this to be persisted in the state.

However, when refreshing state, Terraform detects a change and proposes applying the change again. It is as if "ENTERPRISE" was cleared and set to "", so Terraform will always propose setting the value back to "ENTERPRISE"

I suspect (though have not spent much time verifying) that the server is simply returning "" even though the Terraform provider set "ENTERPRISE." That is, the server treats "" and "ENTERPRISE" as equivalent, but the Terraform provider does not (the provider seems to be treating this field as a tri-state ""/"ENTERPRISE"/"ENTERPRISE_PLUS")

**Comment by DanielRieske** [comment]
@jawnsy So it seems I was still asleep when I read this because I thought this was due to a change I made earlier last week but it seems this was done to a completely different resource.

Your issue is most likely related towards the `machine_type` / `tier` you are using

Enterprise can be used for general purpose machines and Enterprise Plus for high-performance machines.
If the `tier` you are using is neither of them or a shared-core machine type then you cannot use this setting.

It's odd the API doesn't reject it but it's not a valid field to set.

Can you confirm that this is the case or perhaps share the configuration that you are using?

**Comment by jawnsy** [comment]
@DanielRieske These appear as Enterprise in the UI:

![image](https://github.com/hashicorp/terraform-provider-google/assets/52710/97f19108-6f28-489b-9641-b89683c10ce4)

Here's a closer look:

![image](https://github.com/hashicorp/terraform-provider-google/assets/52710/96863e9c-d39b-4cff-9249-f3c8c8b613a0)

I really think the issue is just that, when we set Enterprise via the API, it comes back from the server as an empty string, which is equivalent (because the default edition is Enterprise)

**Comment by jawnsy** [comment]
I think perhaps the behavior is different with existing vs new instances. One of our existing instances has this (redacted) describe output:

```yaml
availableMaintenanceVersions:
- POSTGRES_14_7.R20230530.01_11
backendType: SECOND_GEN
databaseInstalledVersion: POSTGRES_14_7
databaseVersion: POSTGRES_14
gceZone: us-east1-b
instanceType: CLOUD_SQL_INSTANCE
kind: sql#instance
serviceAccountEmailAddress: p286472878979-mkrv9i@gcp-sa-cloud-sql.iam.gserviceaccount.com
settings:
  activationPolicy: ALWAYS
  availabilityType: ZONAL
  backupConfiguration:
    backupRetentionSettings:
      retainedBackups: 7
      retentionUnit: COUNT
    enabled: true
    kind: sql#backupConfiguration
    location: us
    pointInTimeRecoveryEnabled: true
    replicationLogArchivingEnabled: true
    startTime: 11:00
    transactionLogRetentionDays: 7
  connectorEnforcement: NOT_REQUIRED
  dataDiskSizeGb: '168'
  dataDiskType: PD_SSD
  deletionProtectionEnabled: true
  kind: sql#settings
  locationPreference:
    kind: sql#locationPreference
    zone: us-east1-b
  maintenanceWindow:
    day: 6
    hour: 21
    kind: sql#maintenanceWindow
    updateTrack: canary
  pricingPlan: PER_USE
  replicationType: SYNCHRONOUS
  settingsVersion: '133'
  storageAutoResize: true
  storageAutoResizeLimit: '0'
  tier: db-custom-2-8192
  userLabels:
    db_name: events
    region: us-east1
    role: primary
state: RUNNABLE
```

Same output for a new instance I just created:

```yaml
backendType: SECOND_GEN
databaseInstalledVersion: POSTGRES_14_7
databaseVersion: POSTGRES_14
instanceType: CLOUD_SQL_INSTANCE
kind: sql#instance
region: us-east1
settings:
  activationPolicy: ALWAYS
  availabilityType: ZONAL
  backupConfiguration:
    backupRetentionSettings:
      retainedBackups: 7
      retentionUnit: COUNT
    enabled: false
    kind: sql#backupConfiguration
    pointInTimeRecoveryEnabled: false
    replicationLogArchivingEnabled: false
    startTime: 03:00
    transactionLogRetentionDays: 7
  connectorEnforcement: NOT_REQUIRED
  dataDiskSizeGb: '10'
  dataDiskType: PD_SSD
  deletionProtectionEnabled: false
  edition: ENTERPRISE # This isn't in the previous output for the existing instance
  kind: sql#settings
  locationPreference:
    kind: sql#locationPreference
    zone: us-east1-b
  maintenanceWindow:
    day: 1
    hour: 23
    kind: sql#maintenanceWindow
    updateTrack: canary
  pricingPlan: PER_USE
  replicationType: SYNCHRONOUS
  settingsVersion: '1'
  storageAutoResize: true
  storageAutoResizeLimit: '0'
  tier: db-custom-2-8192
state: RUNNABLE
```

It seems like the problem actually is that this value is only set on creation, and modifying it later won't actually modify it.

For example, to reproduce, I used this Terraform file:

```terraform
module "cloudsql" {
  source  = "GoogleCloudPlatform/sql-db/google//modules/postgresql"
  version = "16.0.0"

  name       = local.instance_name
  project_id = local.project_id
  database_version = "POSTGRES_14"

  create_timeout = "15m"
  delete_timeout = "15m"
  update_timeout = "15m"

  ip_configuration = {
    authorized_networks = []
    ipv4_enabled       = false
    private_network    = "https://www.googleapis.com/compute/v1/projects/prefect-sbx-jonathanyu/global/networks/test"
    allocated_ip_range = "private-service-range"
    require_ssl        = false
  }

  availability_type = "ZONAL"
  region            = "us-east1"
  zone              = "us-east1-b"
  tier              = "db-custom-2-8192"
  edition           = "ENTERPRISE"
}
```

If you then change edition to "null" and apply:

```
module "cloudsql" {
  source  = "GoogleCloudPlatform/sql-db/google//modules/postgresql"
  version = "16.0.0"

  name       = local.instance_name
  project_id = local.project_id
  database_version = "POSTGRES_14"

  create_timeout = "15m"
  delete_timeout = "15m"
  update_timeout = "15m"

  ip_configuration = {
    authorized_networks = []
    ipv4_enabled       = false
    private_network    = "https://www.googleapis.com/compute/v1/projects/prefect-sbx-jonathanyu/global/networks/test"
    allocated_ip_range = "private-service-range"
    require_ssl        = false
  }

  availability_type = "ZONAL"
  region            = "us-east1"
  zone              = "us-east1-b"
  tier              = "db-custom-2-8192"
  edition           = null
}
```

Applying the first time, you get this:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.cloudsql.google_sql_database_instance.default will be updated in-place
  ~ resource "google_sql_database_instance" "default" {
        id                             = "jawnsy-test"
        name                           = "jawnsy-test"
        # (14 unchanged attributes hidden)

      ~ settings {
          - edition                     = "ENTERPRISE" -> null
            # (12 unchanged attributes hidden)

            # (4 unchanged blocks hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

Applying again, you get:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.cloudsql.google_sql_database_instance.default will be updated in-place
  ~ resource "google_sql_database_instance" "default" {
        id                             = "jawnsy-test"
        name                           = "jawnsy-test"
        # (14 unchanged attributes hidden)

      ~ settings {
          - edition                     = "ENTERPRISE" -> null
            # (12 unchanged attributes hidden)

            # (4 unchanged blocks hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
