### ISSUE TITLE
google_cloud_run_v2_service and google_cloud_run_v2_job do not support Direct VPC egress with a VPC network

### ISSUE THREAD

**Issue by le0pard** [hashicorp/terraform-provider-google#15568]
### Description

<img width="662" alt="Screenshot 2023-08-19 at 01 45 23" src="https://github.com/hashicorp/terraform-provider-google/assets/98444/47053aba-e0e8-4808-911a-e53687c90122">

Cloud Run v2 have in preview "Direct VPC egress", which based on this comparison https://cloud.google.com/run/docs/configuring/vpc-connect-comparison much better than "Serverless VPC Access connectors"

Problem, that "google_cloud_run_v2_service" in "vpc_access" support only "connector" for "Serverless VPC Access connectors" and "egress" settings. Even if I am try to skip "connector" and only have "egress", I will get error:

```
│ Error: Error updating Service "projects/tests/locations/us-central1/services/test-service": googleapi: Error 400: Violation in UpdateServiceRequest.service.template.vpc_access.connector: one and only one of connector and network_interfaces must be set.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.BadRequest",
│     "fieldViolations": [
│       {
│         "description": "one and only one of connector and network_interfaces must be set.",
│         "field": "Violation in UpdateServiceRequest.service.template.vpc_access.connector"
│       }
│     ]
│   }
│ ]
│
│   with google_cloud_run_v2_service.test_service,
│   on cloud_run.tf line 251, in resource "google_cloud_run_v2_service" "test_service":
│  251: resource "google_cloud_run_v2_service" "test_service" {
```

Same issue have "google_cloud_run_v2_job" resource.

More info about "Direct VPC egress":  https://cloud.google.com/run/docs/configuring/vpc-direct-vpc

### New or Affected Resource(s)

* google_cloud_run_v2_service
* google_cloud_run_v2_job

### Potential Terraform Configuration

I cannot find API call attributes, but I see this payload part, which json payload send GCP UI

```json
// ...
"vpcSettings": {
  "vpcAccessEgress": "private-ranges-only",
  "directVpc": {
    "vpcNetworkInterfaces": [
      {
        "network": "test-vpc",
        "subnetwork": "test-vpc-subnet",
        "tags": [
          "cloud-run"
        ]
      }
    ]
  }
}
```

### References

 - https://cloud.google.com/run/docs/configuring/vpc-connect-comparison
 - https://cloud.google.com/run/docs/configuring/vpc-direct-vpc

b/298050505

**Comment by mrak-** [comment]
Please tell me what is known about this problem? How can it be solved, maybe there is an example?

**Comment by le0pard** [comment]
Hello, right now I solve this by YML file:

```yml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  ...
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '4'
        run.googleapis.com/network-interfaces: '[{"network":"private-network","subnetwork":"subnet","tags":["net"]}]'
        run.googleapis.com/vpc-access-egress: private-ranges-only
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/startup-cpu-boost: 'true'
        run.googleapis.com/sessionAffinity: 'false'
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 20
      timeoutSeconds: '60'
      ...

```

and apply this changes by `gcloud run services replace service.yml`. Also this option available in UI (as I show in screenshot). But not options for terraform @mrak-
