### ISSUE TITLE
Add first-class support for JSON fields in MMv1

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#15796]
# Background

There are currently about 42 JSON fields represented in yaml files, like so:

```
      - !ruby/object:Api::Type::String
        name: field_name
        custom_expand: 'templates/terraform/custom_expand/json_schema.erb'
        custom_flatten: 'templates/terraform/custom_flatten/json_schema.erb'
        state_func:
          'func(v interface{}) string { s, _ :=
          structure.NormalizeJsonString(v); return s }'
        validation: !ruby/object:Provider::Terraform::Validation
          function: 'validation.StringIsJSON'
```

Since this is a common type of field, it could make sense for us to handle it as a standard subtype.

# What kind of contribution is this issue about?

* MMv1-based resource
