### ISSUE TITLE
google_cloudbuild_trigger can't create a real manual invocation

### ISSUE THREAD

**Issue by yerb-loreal** [hashicorp/terraform-provider-google#16295]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Hi,

**The context**

Our project uses two types of triggers:
* "build" triggers to create artifacts (npm modules or Docker images) from from various Git repositories
* "deploy" triggers to deploy Docker images to Cloud Run

We use distinct GCP project for environments (dev, integration, production).
Docker images are generated by a single project and this one has "build" triggers (and "deploy" triggers).
Other projects have only "deploy" triggers (and constraints over images that can be deployed) but no "build" triggers. So it makes no sense for these projects to declare Git repositories as all they need is an access to an artifact registry repository. However...

**The problem**

As far as I know, event with the latest version of the provider (5.2.0 today, beta or not), `google_cloudbuild_trigger` can't be used to create a real manual invocation trigger because

> one of `bitbucket_server_trigger_config,github,pubsub_config,repository_event_config,source_to_build,trigger_template,webhook_config` must be specified`

Here is a screenshot of what I'd like to obtain.

![google_cloudbuild_trigger_manual](https://github.com/hashicorp/terraform-provider-google/assets/129528201/ba16a46c-5ce4-4176-8036-ae4111df8e59)

Here are trigger definitions obtained with `gcloud builds triggers list`.

What I can create with GCP Console (useless but kept simple):
```
build:
  steps:
  - args:
    - echo
    - hello world
    name: ubuntu
createTime: whatever
id: whatever
name: manual-invocation
resourceName: whatever
```

What I can create with `google_cloudbuild_trigger`
using `trigger_template`
```
build:
  steps:
  - args:
    - echo
    - hello world
    name: ubuntu
createTime: whatever
id: whatever
name: not-a-manual-invocation
resourceName: whatever
triggerTemplate:
  branchName: main
  projectId: whatever
  repoName: default
```
using `source_to_build`
```
build:
  steps:
  - args:
    - echo
    - hello world
    name: ubuntu
createTime: whatever
id: whatever
name: not-a-manual-invocation
resourceName: whatever
sourceToBuild:
  ref: refs/heads/main
  repoType: GITHUB
  uri: whatever
```

So, the current workaround is to define "deploy" triggers with `trigger_template` or `source_to_build` but it requires to declare a source repository in every project, even if it's not used.

### New or Affected Resource(s)

* google_cloudbuild_trigger

### Potential Terraform Configuration

```tf
resource "google_cloudbuild_trigger" "manual_invocation" {
  location = var.region
  name     = "manual-invocation"
  build {
    step {
      name = "ubuntu"
      args = ["echo", "hello world"]
    }
  }
  # trigger_template {
  #   branch_name = "main"
  # }
}
```

### References

* https://github.com/GoogleCloudPlatform/magic-modules/pull/5738

b/307910874
