### ISSUE TITLE
google_compute_subnetwork dynamic blocks not allowed for log_config

### ISSUE THREAD

**Issue by Nornode** [hashicorp/terraform-provider-google#16937]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.5.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v5.2.0
+ provider registry.terraform.io/hashicorp/google-beta v5.2.0

```

### Affected Resource(s)

`google_compute_subnetwork`

### Terraform Configuration Files

``` yaml
resource "google_compute_subnetwork" "subnet" {
  for_each = var.subnets != null ? var.subnets : null

  name                     = each.value.name
  ip_cidr_range            = each.key
  region                   = lookup(each.value, "region", var.region)
  network                  = each.value.network
  project                  = var.project
  private_ip_google_access = true
  dynamic "secondary_ip_range" {
    for_each = each.value.secondary_ip_range

    content {
      range_name    = secondary_ip_range.value.name
      ip_cidr_range = secondary_ip_range.value.cidr_range
    }
  }

  dynamic "log_config" {
    for_each = each.value.log_config != null ? each.value.log_config : {}

    content {
      aggregation_interval = lookup(each.value.log_config, "aggregation_interval", null )
      flow_sampling        = lookup(each.value.log_config, "flow_sampling", null )
      metadata             = lookup(each.value.log_config, "metadata", null )
      metadata_fields      = lookup(each.value.log_config, "metadata_fields", null )
      filter_expr          = lookup(each.value.log_config, "filter_expr", null )
    }
  }
}
```

var.subnets
``` yaml
subnets:
  192.168.60.0/24:
    region: europe-west2
    name: thunder
    network: prod
    folder: prod
    private_ip_google_access: true
    log_config: {}
    secondary_ip_range: []
  192.168.61.0/24:
    name: thunder
    region: europe-west1
    network: non-prod
    folder: non_prod
    private_ip_google_access: true
    log_config:
      aggregation_interval: "INTERVAL_15_MIN"
      filter_expr: "true"
      flow_sampling: 0.7
      metadata: "INCLUDE_ALL_METADATA"
    secondary_ip_range: []
  192.168.62.0/24:
    name: thunder
    region: europe-west3
    network: sst
    folder: sst
    private_ip_google_access: true
    secondary_ip_range: []
```

### Debug Output

``` txt
│ Error: Too many log_config blocks
│ 
│   on ../library/base.network.subnet/main.tf line 25, in resource "google_compute_subnetwork" "subnet":
│   25:     content {
│ 
│ No more than 1 "log_config" blocks are allowed
```

### Expected Behavior

Just like Dynamic blocks, enable / disable the log_config settings/ logs collection in this resource.
The error message now isn't correct and should only alert if there are more than one block configured.

### Actual Behavior

Even though a resource has one log_config block configured inside of the map for subnets, I get the error message "no more than 1 ...."

### Steps to Reproduce

1. `terraform apply`
