### ISSUE TITLE
Support for dataproc sessionTemplates  in Vertex Workbench

### ISSUE THREAD

**Issue by lgbaeza** [hashicorp/terraform-provider-google#17664]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

A session template allows to run serverless interactive development through [Dataproc Sessions](https://cloud.google.com/blog/products/data-analytics/making-serverless-spark-even-more-powerful) in Jupyter notebooks, natively integrated with [Vertex AI Workbench](https://cloud.google.com/vertex-ai-workbench).

This feature is missing in Terraform, so WorkBench notebooks intended to run on top of Dataproc serverless, currently cannot be fully deployed with Terraform since users must create on their own the session templates (called runtime templates on the UI). The Dataproc API related to this resource is [SessionTemplate](https://cloud.google.com/dataproc-serverless/docs/reference/rest/v1/projects.locations.sessionTemplates#SessionTemplate)

### New or Affected Resource(s)

* google_workbench_instance

### Potential Terraform Configuration

```tf 
resource "google_dataproc_session_template" "runtime_template" {
  name = "dataproc runtime template"
  description = "Serverless dataproc session to be used on Vertex AI"
  runtimeConfig = {
    containerImage = "gcr.io/my-project/custom-spark:v0.0"
  }
  environmentConfig = {
    executionConfig = {
      serviceAccount = "dataproc-sa@my-project.iam.gserviceaccount.com"
      networkUri = "default"
      subnetworkUri = "default"
    }
  }
}
```

### References

* [Add resources for Vertex AI notebook runtime templates](https://github.com/hashicorp/terraform-provider-google/issues/16429) could look similar, however that issue is for the Workbench notebook runtime, this is for the dataproc runtime used by the notebook.

b/331218090
b/331217910

**Comment by animeshnandanwar** [comment]
Created PR for adding session template resource https://github.com/GoogleCloudPlatform/magic-modules/pull/14201.
@melinath Any idea on what changes are needed on the workbench  ?

**Comment by mrow4a** [comment]
for the ones that cannot upgrade easily and need to use it, there is an easy alternative way

**gcloud module itself:**
```
module "executable_setup_dataproc_interactive_session_templates" {
  # FIXME: terraform google module is pending, see https://github.com/hashicorp/terraform-provider-google/issues/17664 
  source = "terraform-google-modules/gcloud/google"
  version = "~> 3.5"

  upgrade       = false
  skip_download = true

  create_cmd_entrypoint = "${path.module}/dataproc-interactive-session-templates/setup.sh"
  create_cmd_body       = "something@${var.project_id}.iam.gserviceaccount.com ${var.project_id} ${var.region}"
  create_cmd_triggers = {
    setup_script = filemd5("${path.module}/dataproc-interactive-session-templates/setup.sh")
  }
}
```

**script to execute**
```

# Init

IMPERSONATE_SERVICE_ACCOUNT=$1
PROJECT_ID=$2
REGION=$3

GCLOUD_CMD="gcloud --project $PROJECT_ID --verbosity error"

set -e +x

# Set impersonation for gcloud
$GCLOUD_CMD config set auth/impersonate_service_account $IMPERSONATE_SERVICE_ACCOUNT

# Import the template

TEMPLATE_SPARK_BIGQUERY_BASE_NAME="spark-bigquery-base"
$GCLOUD_CMD beta dataproc session-templates import "projects/$PROJECT_ID/locations/$REGION/sessionTemplates/$TEMPLATE_SPARK_BIGQUERY_BASE_NAME" <<EOF
description: $TEMPLATE_SPARK_BIGQUERY_BASE_NAME
environmentConfig:
  executionConfig:
    serviceAccount: something@$PROJECT_ID.iam.gserviceaccount.com
    subnetworkUri: something
  peripheralsConfig: {}
jupyterSession:
  displayName: $TEMPLATE_SPARK_BIGQUERY_BASE_NAME
  kernel: PYTHON
labels:
  client: bigquery-jupyter-plugin
runtimeConfig:
  properties:
    spark.dataproc.driver.disk.size: 400g
    spark.dataproc.driver.disk.tier: standard
    spark.dataproc.executor.disk.size: 400g
    spark.dataproc.executor.disk.tier: standard
    spark.datasource.bigquery.materializationDataset: dataproc
    spark.datasource.bigquery.temporaryGcsBucket: $PROJECT_ID-dataproc-temp
    spark.datasource.bigquery.viewsEnabled: 'true'
    spark.driver.cores: '4'
    spark.driver.memory: 12200m
    spark.driver.memoryOverhead: 1220m
    spark.dynamicAllocation.enabled: 'true'
    spark.dynamicAllocation.executorAllocationRatio: '0.3'
    spark.dynamicAllocation.initialExecutors: '2'
    spark.dynamicAllocation.maxExecutors: '1000'
    spark.dynamicAllocation.minExecutors: '2'
    spark.executor.cores: '4'
    spark.executor.instances: '2'
    spark.executor.memory: 12200m
    spark.executor.memoryOverhead: 1220m
    spark.reducer.fetchMigratedShuffle.enabled: 'false'
  version: '1.2'
EOF

$GCLOUD_CMD config unset auth/impersonate_service_account
```
