### ISSUE TITLE
gcloud: command not found when running gcloud in data external in github workflow environment

### ISSUE THREAD

**Issue by paololazzari** [hashicorp/terraform-provider-google#18047]
### Terraform Version & Provider Version(s)

```
$ terraform version
Terraform v1.7.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/external v2.3.3
+ provider registry.terraform.io/hashicorp/google v5.28.0
+ provider registry.terraform.io/hashicorp/null v3.2.2
```
### Affected Resource(s)

`data "external"`

### Terraform Configuration

In the workflow:

```
- name: 'Install gcloud'
  run: |-
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
    echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
    sudo apt-get update && sudo apt-get install google-cloud-cli

- name: 'Debug'
  run: |-
    gcloud monitoring uptime list-configs # this works
    PATH="$PATH:/usr/lib/google-cloud-sdk/bin/gcloud"

- name: Run plan
  uses: gruntwork-io/terragrunt-action@v2.0.2
  env:
    TF_LOG: TRACE
  with:
    tf_version: '1.5.7'
    tg_version: '0.53.2'
    tg_command: 'run-all plan'
```

In my terraform code:
```tf
data "external" "check_ids" {
  program    = ["bash", "-c", "gcloud monitoring uptime list-configs"]
}
```

### Debug Output

```
│   23:   program    = ["bash", "-c", "gcloud monitoring uptime list-configs"]
│ 
│ The data source received an unexpected error while attempting to execute
│ the program.
│ 
│ Program: /usr/bin/bash
│ Error Message: bash: line 1: gcloud: command not found
│ 
│ State: exit status 127
╵
```
