### ISSUE TITLE
advanced routing rules for External HTTP(s) Load Balancers

### ISSUE THREAD

**Issue by dcardellino24** [hashicorp/terraform-provider-google#18470]
### Question

Hey together,

I have found this issue: https://github.com/hashicorp/terraform-provider-google/issues/6634

According to this issue the following should work or?

```
defaultService: service-a
hostRules:
- hosts:
  - 'example.com'
  pathMatcher: example
kind: compute#urlMap
name: example
pathMatchers:
- defaultService: service-a
  name: example
  routeRules:
  - matchRules:
    - headerMatches:
      - exactMatch: b
        headerName: abtest
      prefixMatch: /
    priority: 1
    service: service-a
```

Because in terraform documentation there is still: `routeRules are not supported in UrlMaps intended for External load balancers.`

Thanks in advance,

Dominic
