### ISSUE TITLE
Google Artifact Registry support for `common_repository`

### ISSUE THREAD

**Issue by joemiller** [hashicorp/terraform-provider-google#20278]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Allow creating `remote` repositories using the `commonRepository` config from terraform.

The goal here would be to create pull-through mirrors of other GAR registries. For example, imagine a central docker `dev` repository in the `us-central1` location and you want to create regional caches in other regions, eg: `asia-northeast1`, `europe-west2`, etc.

This can be done from the web console or gcloud CLI, but does not appear possible from Terraform.

I have only experimented with this using Docker repositories. It might be possible with the other types.

In the web console when creating a new repository and selecting `Docker` + `Remote` you are presented with an option `Artifact Registry repository` which takes a path to an existing repository in the form `projects/UPSTREAM_PROJECT_ID/locations/REGION/repositories/UPSTREAM_REPOSITORY`

<img width="550" alt="image" src="https://github.com/user-attachments/assets/5b733224-2479-41dc-84e9-3416283c4099">

Or from `gcloud` CLI using the flag `--remote-docker-repo=projects/UPSTREAM_PROJECT_ID/locations/REGION/repositories/UPSTREAM_REPOSITORY` to `gcloud artifacts repositories create`. See [here](https://cloud.google.com/artifact-registry/docs/repositories/remote-repo#create-gcloud)

I tried a resource similar to this:

```tf
resource "google_artifact_registry_repository" "my-repo" {
  location      = "us-central1"
  repository_id = "my-repository"
  description   = "example remote docker repository"
  format        = "DOCKER"
  mode          = "REMOTE_REPOSITORY"
  remote_repository_config {
    docker_repository {
      custom_repository = {
         uri = "projects/UPSTREAM_PROJECT_ID/locations/REGION/repositories/UPSTREAM_REPOSITORY"
      }
    }
  }
}
```

But this results in an API error:
```
Error: Error creating Repository: googleapi: Error 400: Custom remote repository URI must start with 'http://' or 'https://'
```

Describing a repo created thru the console shows this (relevant parts only):

```yaml
#  gcloud artifacts repositories describe dev --location=us-central1 
Encryption: Google-managed key
Registry URL: us-central1-docker.pkg.dev/xxxxxxxx-registry/dev
format: DOCKER
mode: REMOTE_REPOSITORY
name: projects/xxxxxxx-registry/locations/us-central1/repositories/dev
remoteRepositoryConfig:
  commonRepository:
    uri: projects/xxxxxxx-registry/locations/us/repositories/dev
```

Comparing that to a remote repository that points to quay.io:

```yaml
# gcloud artifacts repositories describe quay 
format: DOCKER
mode: REMOTE_REPOSITORY
name: projects/xxxxxxx-registry/locations/us-central1/repositories/quay
remoteRepositoryConfig:
  description: Cache public quay.io images
  dockerRepository:
    customRepository:
      uri: https://quay.io
```

There is a difference in the `remoteRepositoryConfig` structure that leads me to believe the issue might be a lack of a `common_repository` config for `remote_repository`.

If there is a way to configure a remote repository with the current provider, please let me know and consider updating the docs. Or, if not, it would be great to add support for this in the provider.

### New or Affected Resource(s)

* google_artifact_registry_repository

### Potential Terraform Configuration

```tf
resource "google_artifact_registry_repository" "my-repo" {
  location      = "us-central1"
  repository_id = "my-repository"
  description   = "example remote docker repository"
  format        = "DOCKER"
  mode          = "REMOTE_REPOSITORY"
  remote_repository_config {
    common_repository {
       uri = "projects/UPSTREAM_PROJECT_ID/locations/REGION/repositories/UPSTREAM_REPOSITORY"
    }
  }
}
```

This matches the output from `gcloud artifacts repositories describe`

### References

https://cloud.google.com/artifact-registry/docs/repositories/remote-repo#create-gcloud

b/378495989
