### ISSUE TITLE
Reintroduce deprecated enable-network-flow-logs field in terraform-google-provider

### ISSUE THREAD

**Issue by renato-rudnicki** [hashicorp/terraform-provider-google#21950]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.5.7
on Ubuntu 22.04.4 LTS
+ provider registry.terraform.io/hashicorp/google v6.26.0
+ provider registry.terraform.io/hashicorp/google-beta v6.26.0

### Affected Resource(s)

terraform-example-foundation/policy-library/policies/constraints/network_enable_flow_logs.yaml

### Terraform Configuration

We are hitting in the following error during the deployment of 0-bootstrap on terraform-example-foundation:

```tf
provider "google-beta" {
  user_project_override = true
  billing_project       = var.groups.billing_project
}
```

### Actual Behavior

```tf
constraint: GCPNetworkEnableFlowLogsConstraintV1.enable_network_flow_logs
constraint_config:
  api_version: constraints.gatekeeper.sh/v1alpha1
  kind: GCPNetworkEnableFlowLogsConstraintV1
  metadata:
    annotations:
      validation.gcp.forsetisecurity.org/originalName: enable_network_flow_logs
      validation.gcp.forsetisecurity.org/yamlpath: ../policy-library/policies/constraints/network_enable_flow_logs.yaml
    name: enable-network-flow-logs
  spec:
    match:
      gcp:
        target:
        - organizations/**
    parameters: {}
    severity: high
message: Flow logs are disabled in subnetwork //compute.googleapis.com/projects/prj-feature-standalone/regions/us-central1/subnetworks/sb-b-cbpools-us-central1.
metadata:
  ancestry_path: organizations/1055058813388/folders/616710121893/folders/577514760483/projects/prj-feature-standalone
  constraint:
    annotations:
      validation.gcp.forsetisecurity.org/originalName: enable_network_flow_logs
      validation.gcp.forsetisecurity.org/yamlpath: ../policy-library/policies/constraints/network_enable_flow_logs.yaml
    labels: {}
    parameters: {}
  details:
    resource: //compute.googleapis.com/projects/prj-feature-standalone/regions/us-central1/subnetworks/sb-b-cbpools-us-central1
resource: //compute.googleapis.com/projects/prj-feature-standalone/regions/us-central1/subnetworks/sb-b-cbpools-us-central1
severity: high
```

### Steps to reproduce

```
terraform init
terraform plan -input=false -out bootstrap.tfplan
export VET_PROJECT_ID=A-VALID-PROJECT-ID
terraform show -json bootstrap.tfplan > bootstrap.json
gcloud beta terraform vet bootstrap.json --policy-library="../policy-library" --project ${VET_PROJECT_ID}
```

### Important Factoids

```
constraint: GCPNetworkEnableFlowLogsConstraintV1.enable_network_flow_logs
constraint_config:
  api_version: constraints.gatekeeper.sh/v1alpha1
  kind: GCPNetworkEnableFlowLogsConstraintV1
  metadata:
    annotations:
      validation.gcp.forsetisecurity.org/originalName: enable_network_flow_logs
      validation.gcp.forsetisecurity.org/yamlpath: ../policy-library/policies/constraints/network_enable_flow_logs.yaml
    name: enable-network-flow-logs
  spec:
    match:
      gcp:
        target:
        - organizations/**
    parameters: {}
    severity: high
message: Flow logs are disabled in subnetwork //compute.googleapis.com/projects/prj-feature-standalone/regions/us-central1/subnetworks/sb-b-cbpools-us-central1.
metadata:
  ancestry_path: organizations/1055058813388/folders/616710121893/folders/577514760483/projects/prj-feature-standalone
  constraint:
    annotations:
      validation.gcp.forsetisecurity.org/originalName: enable_network_flow_logs
      validation.gcp.forsetisecurity.org/yamlpath: ../policy-library/policies/constraints/network_enable_flow_logs.yaml
    labels: {}
    parameters: {}
  details:
    resource: //compute.googleapis.com/projects/prj-feature-standalone/regions/us-central1/subnetworks/sb-b-cbpools-us-central1
resource: //compute.googleapis.com/projects/prj-feature-standalone/regions/us-central1/subnetworks/sb-b-cbpools-us-central1
severity: high
```

As seen in the references below, the field `enable-network-flow-logs` was deprecated and removed from the terraform-google-provider in the release 3.90.0 (October 26, 2021)

https://github.com/GoogleCloudPlatform/magic-modules/pull/2597 - Update subnetwork to remove enable_flow_logs and depend on log_config

https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG_v3.md#300-beta1-november-15-2019 - compute: removed enable_flow_logs field from google_compute_subnetwork. This is now controlled by the presence of the log_config block MM#2597

However, this field was reintroduced in the latest release of terraform-google-provider v6.26.0 as we can see in the following references:

https://github.com/hashicorp/terraform-provider-google/pull/21851 - Feature gap: Add missed enable_flow_logs & state to subnetwork

https://github.com/hashicorp/terraform-provider-google/releases/tag/v6.26.0 - compute: added enable_flow_logs and state fields to google_compute_subnetwork resource (#21851) 

This is affecting both terraform-provider-google and terraform-provider-google-beta.

### References

https://github.com/GoogleCloudPlatform/magic-modules/pull/2597
https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG_v3.md#300-beta1-november-15-2019
https://github.com/terraform-google-modules/terraform-google-network/issues/105
https://github.com/hashicorp/terraform-provider-google/pull/21851
