### ISSUE TITLE
`write-only`: eliminate need to manually add *_wo and *_wo_version fields

### ISSUE THREAD

**Issue by BBBmau** [hashicorp/terraform-provider-google#23213]
### What kind of contribution is this issue about?

Other (specify in details)

### Details

ensure that when setting a property to `write_only: true` we should have a `*_wo_version` property generated at the same level as the write-only property.

Also ensure that we can support `immutable: true` with write_only attributes where it sets the `*_wo_version` as immutable (ForceNew)

**Comment by melinath** [comment]
per discussion today we actually want to generate both the `*_wo` and `*_wo_version` fields.

**Comment by melinath** [comment]
Desired end-user config would look like:

```yaml
- name: 'password'
    type: String
    description: |
      foo
    ignore_read: true
    sensitive: true
    write_only: true
```

This would automatically generate `password_wo` and `password_wo_version`.
