### ISSUE TITLE
Cloud Build - no Build Secret field but secret_env is available in steps

### ISSUE THREAD

**Issue by joshua9519** [hashicorp/terraform-provider-google#4844]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

According to the [documentation](https://www.terraform.io/docs/providers/google/r/cloudbuild_trigger.html#secret_env), the secret_env values need to be specified by the build's `Secret`.  
However, this field does not exist. I don't see how to define a `secret_env` without this field existing.

### New or Affected Resource(s)

* google_cloudbuild_trigger
### Potential Terraform Configuration

```tf
google_cloudbuild_trigger "x" {
  build {
    secrets = [
        {
            kms_key_name = projects/project_id/locations/global/keyRings/keyring_name/cryptoKeys/key_name
            secret_env = {
                SECRET = "encrypted string"
            }
        }
    ]
  }
}      
```

### References

* #0000

**Comment by jackivanov** [comment]
Any progress on this one?

**Comment by wyardley** [comment]
FWIW, I seem to be able to do it without anything special in the trigger, e.g.,
```yaml
steps:
  - args:
      - build
      - .
      - '--build-arg'
      - 'FOO'
    name: gcr.io/cloud-builders/docker
    secretEnv: ['FOO']
[....]
availableSecrets:
  secretManager:
    - versionName: projects/bar/secrets/foo/versions/latest
      env: FOO
```

see docs in
https://cloud.google.com/build/docs/securing-builds/use-secrets
