### ISSUE TITLE
Creating CloudSQL with same name as deleted CloudSQL still having issues in v3.13.0

### ISSUE THREAD

**Issue by syedrakib** [hashicorp/terraform-provider-google#6066]
### References

I had [previously commented](https://github.com/terraform-providers/terraform-provider-google/issues/5101#issuecomment-603384185) on a pre-existing issue #5101. But the issue was **closed** saying it is resolved in Google provider version **v3.3**. Turns out it's not yet resolved in Google provider version **v3.13.0**

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.24
+ provider.google v3.13.0
+ provider.google-beta v3.13.0
```

### Affected Resource(s)

* google_sql_database_instance - [link](https://www.terraform.io/docs/providers/google/r/sql_database_instance.html)

### Terraform Configuration Files

Official Google Terraform module for CloudSQL MySQL - [link](https://github.com/terraform-google-modules/terraform-google-sql-db/blob/v3.1.0/modules/mysql/main.tf)

### Debug Output

```
module.my_infra.module.mysql_db.google_sql_database_instance.default: Still creating... [9m20s elapsed]
module.my_infra.module.mysql_db.google_sql_database_instance.default: Still creating... [9m30s elapsed]
module.my_infra.module.mysql_db.google_sql_database_instance.default: Still creating... [9m40s elapsed]
module.my_infra.module.mysql_db.google_sql_database_instance.default: Still creating... [9m50s elapsed]

Error: Error, failed to create instance mysql-rakib-dev: googleapi: Error 409: The instance or operation is not in an appropriate state to handle the request., invalidState

  on .terraform/modules/my_infra.mysql_db/terraform-google-sql-db-3.1.0/modules/mysql/main.tf line 27, in resource "google_sql_database_instance" "default":
  27: resource "google_sql_database_instance" "default" {
```

**"Still creating..."** for 10 minutes until it timed out.

### Steps to Reproduce

* Create a CloudSQL instance with a specific name
* Delete the CloudSQL instance
* Try to recreate another CloudSQl instance with the same name.

### Current Behavior

It kept trying for 10 minutes (until timeout) and then errored out with a `failed to create instance` error.

### Expected Behavior

Terraform shouldn't hang like this until timeout (which was 10 minutes here). Instead, terraform could try for some time and then fail saying [this](https://cloud.google.com/sql/docs/mysql/delete-instance) is a probable cause and the developer should verify.

### Reference

[This GCloud doc](https://cloud.google.com/sql/docs/mysql/delete-instance) says "You cannot reuse an instance name for up to a week after you have deleted an instance".

**Comment by edwardmedia** [comment]
Can we stop retrying earlier if this msg is received?

**Comment by venkykuberan** [comment]
@syedrakib you can't use same name for sql instance for a week even after deleting it. GCP does some clean up process in the background to clear all the references.

**Comment by syedrakib** [comment]
Any development with this?

**Comment by megan07** [comment]
Hi @syedrakib!  Sorry for the delayed response, we are looking into it.  The problem is that the API responds with a `409` error, which means two different things for this endpoint, either "the sql instance is undergoing another change and when it's finished we will retry the request" _or_ "a sql instance with the same name has been deleted and the name cannot be reused for a week".
When the issue was first addressed in December, the API was returning a different message in it's response depending on which of those cases it was, however, there must have been a change recently that the response message is now `The instance or operation is not in an appropriate state to handle the request.` Thus, from our side, we can't distinguish a difference between those cases.  We're waiting to hear back from the team at Google to figure out next steps.
Thanks!

**Comment by syedrakib** [comment]
Thanks for the update. Closely following this :)

**Comment by kirin-13** [comment]
> * specific

Encountered the same problem as you. In the test, the instance name contains a random string, and an error is reported when updating the instance. The instance name does not contain a random string, and the instance configuration can be successfully updated. 
I don't know if it will help you solve the problem.

**Comment by syedrakib** [comment]
hi @kirin-13 . I am not sure i understand you. What random string are you talking about?

Just to re-iterate, we are facing this issues when i have deleted a CloudSQL instance and then trying to create a new CloudSQL instance with the **"same" name** as the deleted instance's name.

**Comment by y0ssar1an** [comment]
I worked around this problem by appending a random string to the name of the db on creation.

```terraform
resource "google_sql_database_instance" "main_primary" {
  name = "main-primary-${random_string.four_chars.result}"
}

resource "random_string" "four_chars" {
  length  = 4
  upper   = false # instance names can only have lowercase letters, numbers, and hyphens
  special = false
}
```

**Comment by syedrakib** [comment]
hi @y0ssar1an . This workaround may not completely work.

If you delete the `google_sql_database_instance.main_primary` resource and then re-create that resource, you have a new db_instance resource. 

However, the `random_string.four_chars` was never destroyed and re-created. So the `four_chars` resource will still return the same output as before and, thus, back to the same problem again.

**Comment by syedrakib** [comment]
BTW, this GitHub issue is raised here so that the prodvider fails early and creates a meaningful error message if the CloudSQL name is the issue instead of having to wait forever as it is currently behaving now.

**Comment by y0ssar1an** [comment]
I see the concern. It hasn't been an issue though. I've got the `random_string` and `google_sql_database_instance` together in a module. They always get created and destroyed together.

**Comment by stepanstipl** [comment]
It would be interesting to know how _gcloud_ cli implements this, it returns different error messages depending whether the instance exists(ed) in the same zone or different one:
```console
# same zone
$gcloud sql instances create test-01 --zone us-east1-b
ERROR: (gcloud.sql.instances.create) Resource in project [xxx-redacted] is the subject of a conflict: The Cloud SQL instance already exists. When you delete an instance, you cannot reuse the name of the deleted instance until one week from the deletion date.


# different zone
$gcloud sql instances create test-01 --zone europe-west4-a
ERROR: (gcloud.sql.instances.create) Resource in project [xxx-redacted] is the subject of a conflict: The instance or operation is not in an appropriate state to handle the request.
```

**Comment by syedrakib** [comment]
> It would be interesting to know how _gcloud_ cli implements this, it returns different error messages depending whether the instance exists(ed) in the same zone or different one:
> 
> ```
> # same zone
> $gcloud sql instances create test-01 --zone us-east1-b
> ERROR: (gcloud.sql.instances.create) Resource in project [xxx-redacted] is the subject of a conflict: The Cloud SQL instance already exists. When you delete an instance, you cannot reuse the name of the deleted instance until one week from the deletion date.
> 
> 
> # different zone
> $gcloud sql instances create test-01 --zone europe-west4-a
> ERROR: (gcloud.sql.instances.create) Resource in project [xxx-redacted] is the subject of a conflict: The instance or operation is not in an appropriate state to handle the request.
> ```

this could be something to consider for a start. Especially since @megan07 mentioned [here](https://github.com/terraform-providers/terraform-provider-google/issues/6066#issuecomment-614071479) that the error messages for 2 different cases are being the same right now.

**Comment by syedrakib** [comment]
Reviving this issue. Faced it again today after a long time 😭😭😭

The error being reported now is 

```
Error: Error, failed to create instance my-cloudsql-db: googleapi: Error 409: The instance or operation is not in an appropriate state to handle the request., invalidState
```

Terraform version: **0.12.28**
Google provider version: **3.27.0**

**Comment by vgomenyuk** [comment]
The same issue for v 3.51.0.
`Error: Error, failed to create instance temp-cloud-sql-db-1-stg: googleapi: Error 409: The Cloud SQL instance already exists. When you delete an instance, you cannot reuse the name of the deleted instance until one week from the deletion date., instanceAlreadyExists`

**Comment by rocpoc** [comment]
Same issue for 3.54.0 😢 . Does anyone have workarounds or fixes for this?

`Error: Error, failed to create instance voter-app-prod-database-instance: googleapi: Error 409: The Cloud SQL instance already exists. When you delete an instance, you cannot reuse the name of the deleted instance until one week from the deletion date., instanceAlreadyExists`

**Comment by itspngu** [comment]
Still present for `Terraform` 0.14.9 and `google + google-beta` 3.62.0. Creation of an instance with a previously used name hangs for 20 minutes until it errors out.

Looking at the comments in this issue as well as #5101 - if fixing this is non-trivial, would lowering that timeout to a more... "reasonable" level (possibly only when `TF_IN_AUTOMATION` is not set) be an option until this is solved? The provider handling it (given the info it gets, correctly) as a `retryable` error results in terraform refusing to cleanly shut down a running operation until the creation of the instance times out, which is an extra annoyance as SIGKILLing Terraform processes is not a good idea.

The creation timeout can be specified manually (see below) but that's a) deeply buried in the [docs for the provider](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#timeouts) and b) potentially creates a lot of clutter in people's configurations, so maybe this is worth considering.

```hcl
resource "google_sql_database_instance" "db1" {
  # [...]

  timeouts {
    # According to the docs this is 30 minutes, but in my testing occurs after 20 minutes
    create = "5m"
  }
}
```

Extra snippets of debug output to help those looking into the issue:

`$ terraform apply`

<details>
<summary>Click to expand</summary>

```shell
Error: Error, failed to create instance pg-master: googleapi: Error 409: The Cloud SQL instance already exists. When you delete an instance, you can't reuse the name of the deleted instance until one week from the deletion date., instanceAlreadyExists

  on postgres.tf line 7, in resource "google_sql_database_instance" "pg-master":
   7: resource "google_sql_database_instance" "pg-master" {
```
</details>

`$ TF_LOG=TRACE terraform apply`

<details>
<summary>Click to expand</summary>

```shell
2021-04-07T14:30:34.096+0100 [INFO]  plugin.terraform-provider-google-beta_v3.62.0_x5: 2021/04/07 14:30:34 [INFO] Instantiating Google SqlAdmin client for path https://sqladmin.googleapis.com/: timestamp=2021-04-07T14:30:34.096+0100
2021-04-07T14:30:34.097+0100 [INFO]  plugin.terraform-provider-google-beta_v3.62.0_x5: 2021/04/07 14:30:34 [DEBUG] Retry Transport: starting RoundTrip retry loop: timestamp=2021-04-07T14:30:34.096+0100
2021-04-07T14:30:34.097+0100 [INFO]  plugin.terraform-provider-google-beta_v3.62.0_x5: 2021/04/07 14:30:34 [DEBUG] Retry Transport: request attempt 0: timestamp=2021-04-07T14:30:34.096+0100
2021-04-07T14:30:34.097+0100 [INFO]  plugin.terraform-provider-google-beta_v3.62.0_x5: 2021/04/07 14:30:34 [DEBUG] Google API Request Details:
---[ REQUEST ]---------------------------------------
POST /sql/v1beta4/projects/XXXXXXXX/instances?alt=json&prettyPrint=false HTTP/1.1
Host: sqladmin.googleapis.com
User-Agent: google-api-go-client/0.5 Terraform/0.14.9 (+https://www.terraform.io) Terraform-Plugin-SDK/2.4.4 terraform-provider-
[...]
{
 "databaseVersion": "POSTGRES_13",
 "name": "pg-master",
 "region": "europe-west3",
 "settings": {
  "availabilityType": "ZONAL",
  "backupConfiguration": {
   "binaryLogEnabled": false,
   "enabled": true,
   "pointInTimeRecoveryEnabled": true
  },
  "databaseFlags": [
   {
    "name": "cloudsql.iam_authentication",
    "value": "on"
   }
  ],
  "insightsConfig": {
   "queryInsightsEnabled": true,
   "queryStringLength": 4096
  },
  "ipConfiguration": {
   "ipv4Enabled": true,
   "privateNetwork": "projects/XXXXXXXX/global/networks/default",
   "requireSsl": true
  },
  "locationPreference": {
   "zone": "europe-west3-b"
  },
  "maintenanceWindow": {
   "day": 2,
   "hour": 2
  },
  "pricingPlan": "PER_USE",
  "storageAutoResize": true,
  "tier": "db-custom-1-4096"
 }
}

-----------------------------------------------------: timestamp=2021-04-07T14:30:34.097+0100
2021-04-07T14:30:34.417+0100 [INFO]  plugin.terraform-provider-google-beta_v3.62.0_x5: 2021/04/07 14:30:34 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 409 Conflict
[...]
{
  "error": {
    "code": 409,
    "message": "The Cloud SQL instance already exists. When you delete an instance, you can't reuse the name of the deleted instance until one week from the deletion date.",
    "errors": [
      {
        "message": "The Cloud SQL instance already exists. When you delete an instance, you can't reuse the name of the deleted instance until one week from the deletion date.",
        "domain": "global",
        "reason": "instanceAlreadyExists"
      }
    ]
  }
}

-----------------------------------------------------: timestamp=2021-04-07T14:30:34.417+0100
2021-04-07T14:30:34.417+0100 [INFO]  plugin.terraform-provider-google-beta_v3.62.0_x5: 2021/04/07 14:30:34 [DEBUG] Retry Transport: Stopping retries, last request failed with non-retryable error: googleapi: got HTTP response code 409 with body: HTTP/2.0 409 Conflict
[...]
{
  "error": {
    "code": 409,
    "message": "The Cloud SQL instance already exists. When you delete an instance, you can't reuse the name of the deleted instance until one week from the deletion date.",
    "errors": [
      {
        "message": "The Cloud SQL instance already exists. When you delete an instance, you can't reuse the name of the deleted instance until one week from the deletion date.",
        "domain": "global",
        "reason": "instanceAlreadyExists"
      }
    ]
  }
}: timestamp=2021-04-07T14:30:34.417+0100
2021-04-07T14:30:34.417+0100 [INFO]  plugin.terraform-provider-google-beta_v3.62.0_x5: 2021/04/07 14:30:34 [DEBUG] Retry Transport: Returning after 1 attempts: timestamp=2021-04-07T14:30:34.417+0100
2021-04-07T14:30:34.417+0100 [INFO]  plugin.terraform-provider-google-beta_v3.62.0_x5: 2021/04/07 14:30:34 [DEBUG] Dismissed an error as retryable. Waiting for other concurrent Cloud SQL operations to finish - googleapi: Error 409: The Cloud SQL instance already exists. When you delete an instance, you can't reuse the name of the deleted instance until one week from the deletion date., instanceAlreadyExists: timestamp=2021-04-07T14:30:34.417+0100
2021-04-07T14:30:34.417+0100 [INFO]  plugin.terraform-provider-google-beta_v3.62.0_x5: 2021/04/07 14:30:34 [TRACE] Waiting 10s before next try:  #timestamp=2021-04-07T14:30:34.417+0100
```
</details>

`$ gcloud alpha logging tail projects/XXXXXXXX/logs/cloudaudit.googleapis.com%2Factivity`

<details>
<summary>Click to expand</summary>

```yaml
logName: projects/XXXXXXXX/logs/cloudaudit.googleapis.com%2Factivity
protoPayload:
  '@type': type.googleapis.com/google.cloud.audit.AuditLog
  authenticationInfo:
    principalEmail: terraform@XXXXXXXX.iam.gserviceaccount.com
    serviceAccountKeyName: //iam.googleapis.com/projects/XXXXXXXX/serviceAccounts/terraform@XXXXXXXX.iam.gserviceaccount.com/keys/XXXXXXXX
  authorizationInfo:
  - granted: true
    permission: cloudsql.instances.create
    resource: instances/XXXXXXXX:pg-master
    resourceAttributes: {}
  methodName: cloudsql.instances.create
  request:
    '@type': type.googleapis.com/google.cloud.sql.v1beta4.SqlInstancesInsertRequest
    body:
      databaseVersion: POSTGRES_13
      name: pg-master
      region: europe-west3
      settings:
        availabilityType: ZONAL
        backupConfiguration:
          binaryLogEnabled: false
          enabled: true
          pointInTimeRecoveryEnabled: true
        databaseFlags:
        - name: cloudsql.iam_authentication
          value: on
        insightsConfig:
          queryInsightsEnabled: true
          queryStringLength: 4096.0
        ipConfiguration:
          ipv4Enabled: true
          privateNetwork: projects/XXXXXXXX/global/networks/default
          requireSsl: true
        locationPreference:
          zone: europe-west3-b
        maintenanceWindow:
          day: 2.0
          hour: 2.0
        pricingPlan: PER_USE
        storageAutoResize: true
        tier: db-custom-1-4096
    project: XXXXXXXX
  requestMetadata:
    callerIp: XXXXXXXX
    destinationAttributes: {}
    requestAttributes:
      auth: {}
      time: '2021-04-07T13:11:49.374131Z'
  resourceName: instances/XXXXXXXX:pg-master
  response: {}
  serviceName: cloudsql.googleapis.com
  status:
    code: 6
    message: The Cloud SQL instance [pg-master] already exists. When you delete an
      instance, you cannot reuse the name of the deleted instance until one week from
      the deletion date
receiveTimestamp: '2021-04-07T13:11:49.640972076Z'
resource:
  labels:
    database_id: XXXXXXXX:pg-master
    project_id: XXXXXXXX
    region: europe-west3
  type: cloudsql_database
severity: ERROR
timestamp: '2021-04-07T13:11:49.360880Z'
```
</details>
