### ISSUE TITLE
Creating Cloud Monitoring alert policy

### ISSUE THREAD

**Issue by debakkerb** [hashicorp/terraform-provider-google#6732]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.26

### Affected Resource(s)

* google_monitoring_alert_policy

### Terraform Configuration Files

```tf
resource "google_monitoring_alert_policy" "firewall_hit_count" {
  project = module.stackdriver_workspace_project.project_id

  combiner     = "OR"
  display_name = "Deny Firewall Hit Count"
  enabled      = true

  documentation {
    content = "Hit count for Firewall with DENY rules added increased by 100%."
  }

  notification_channels = [
    google_monitoring_notification_channel.email_notification.id,
    google_monitoring_notification_channel.sms_notification.id
  ]

  conditions {
    display_name = "VM Firewall hit count"

    condition_threshold {
      filter          = "metric.type=\"firewallinsights.googleapis.com/vm/firewall_hit_count\" resource.type=\"gce_instance\" metric.label.firewall_name=\"deny-public-access\""
      threshold_value = "1.0"
      duration        = "0s"
      comparison      = "COMPARISON_GT"

      trigger {
        percent = 1
      }

      aggregations {
        alignment_period   = "60s"
        per_series_aligner = "ALIGN_RATE"
      }

      aggregations {
        alignment_period   = "60s"
        per_series_aligner = "ALIGN_PERCENT_CHANGE"
      }
    }
  }
}
```

### Expected Behavior

The expected behaviour is that an alert policy is created, which is visible in the UI (preferably with a visible diagram for the specific metric).

### Actual Behavior

This is where it becomes a bit weird.  The alert policy is created, however it looks vastly different from the same alert policy configured manually.  I exported a manual one and the one created via Terraform in YAML, and the configuration looks exactly the same:

**Manual Alert Policy**

```yaml
combiner: OR
conditions:
- conditionThreshold:
    aggregations:
    - alignmentPeriod: 60s
      perSeriesAligner: ALIGN_RATE
    - alignmentPeriod: 60s
      perSeriesAligner: ALIGN_PERCENT_CHANGE
    comparison: COMPARISON_GT
    duration: 0s
    filter: metric.type="firewallinsights.googleapis.com/vm/firewall_hit_count" resource.type="gce_instance" metric.label."firewall_name"="deny-public-access"
    thresholdValue: 1.0
    trigger:
      count: 1
  displayName: Deny Firewall Rule Hit Count
  name: projects/PROJECT_ID/alertPolicies/10286332249485509/conditions/10286276249488906
creationRecord:
  mutateTime: '2020-06-26T15:27:37.763125424Z'
  mutatedBy:
displayName: Manual
documentation:
  content: Firewall hit count
  mimeType: text/markdown
enabled: true
mutationRecord:
  mutateTime: '2020-06-29T15:53:47.510766230Z'
  mutatedBy:
name: projects/PROJECT_ID/alertPolicies/1028627633224509
notificationChannels:
- projects/PROJECT_ID/notificationChannels/1776367394198524
```

**Created via Terraform**

```yaml
combiner: OR
conditions:
- conditionThreshold:
    aggregations:
    - alignmentPeriod: 60s
      perSeriesAligner: ALIGN_RATE
    - alignmentPeriod: 60s
      perSeriesAligner: ALIGN_PERCENT_CHANGE
    comparison: COMPARISON_GT
    duration: 0s
    filter: metric.type="firewallinsights.googleapis.com/vm/firewall_hit_count" resource.type="gce_instance" metric.label."firewall_name"="deny-public-access"
    thresholdValue: 1.0
    trigger:
      count: 1
  displayName: VM Firewall hit count
  name: projects/PROJECT_ID/alertPolicies/102502092401796/conditions/105502092400659
creationRecord:
  mutateTime: '2020-06-26T15:36:16.347821794Z'
  mutatedBy: 9927922@cloudbuild.gserviceaccount.com
displayName: Deny Firewall Hit Count
documentation:
  content: Hit count for Firewall with DENY rules added increased by 100%.
  mimeType: text/markdown
enabled: true
mutationRecord:
  mutateTime: '2020-06-29T16:05:54.770561481Z'
  mutatedBy: 9957922@cloudbuild.gserviceaccount.com
name: projects/PROJECT_ID/alertPolicies/102130255021796
notificationChannels:
- projects/PROJECT_ID/notificationChannels/1776367394198524
- projects/PROJECT_ID/notificationChannels/1161437941945234
```

However, in the UI, they look completely different.

**Manual**

- [Manual alert policy](https://photos.app.goo.gl/FZe9jWpRP3FiYDgJ6)
- [Manual alert policy details](https://photos.app.goo.gl/J1PuAbuTGcjQv43x8)

**Via Terraform**

- [Terraform alert policy](https://photos.app.goo.gl/9e7djuLBQoHabfmh9)
- [Terraform alert policy Manual](https://photos.app.goo.gl/TKq16tAHGoyPzZjs5)

### Steps to Reproduce

**Prerequisites**

I'm going to list the steps here, as it may help other people to quickly reproduce the problem.  The steps are to create a project with a network and VM and a Firewall rule that denies all INGRESS traffic.

```tf
module "host_project_a" {
  source  = "terraform-google-modules/project-factory/google"
  version = "~> 8.0"

  name                 = "host-a"
  random_project_id    = true
  org_id               = local.organization_id
  folder_id            = local.sandbox_folder_id
  billing_account      = local.billing_account_id
  skip_gcloud_download = true
  activate_apis = [
    "compute.googleapis.com",
    "dns.googleapis.com",
    "firewallinsights.googleapis.com",
    "networkmanagement.googleapis.com"
  ]
}

module "service_project_a" {
  source  = "terraform-google-modules/project-factory/google"
  version = "~> 8.0"

  name                 = "service-a"
  random_project_id    = true
  org_id               = local.organization_id
  billing_account      = local.billing_account_id
  folder_id            = local.sandbox_folder_id
  skip_gcloud_download = true
  activate_apis = [
    "compute.googleapis.com",
    "firewallinsights.googleapis.com",
    "networkmanagement.googleapis.com"
  ]
}

resource "google_compute_network" "network_a" {
  project                 = module.host_project_a.project_id
  name                    = "host-nw-a"
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "subnetwork_a" {
  project                  = module.host_project_a.project_id
  ip_cidr_range            = "10.0.0.0/24"
  name                     = "host-sn-a"
  network                  = google_compute_network.network_a.self_link
  region                   = "europe-west1"
  private_ip_google_access = true

  log_config {
    aggregation_interval = "INTERVAL_5_SEC"
    flow_sampling        = "1.0"
    metadata             = "INCLUDE_ALL_METADATA"
  }
}

resource "google_compute_shared_vpc_host_project" "host_project_a" {
  project = module.host_project_a.project_id
}

resource "google_compute_shared_vpc_service_project" "service_project_a" {
  host_project    = module.host_project_a.project_id
  service_project = module.service_project_a.project_id
}

resource "google_service_account" "vm_service_account" {
  project      = module.service_project_a.project_id
  account_id   = "public-deny-vm-sa"
  display_name = "Service account to attach to a VM with public IP address, but no open firewall rules."
}

data "google_compute_image" "debian" {
  project = "debian-cloud"
  family  = "debian-9"
}

resource "google_compute_instance" "test_vm" {
  project                   = module.service_project_a.project_id
  machine_type              = "n1-standard-1"
  name                      = "test-vm"
  zone                      = "europe-west1-b"
  allow_stopping_for_update = true

  tags = [
    "deny-public-access"
  ]

  boot_disk {
    initialize_params {
      image = data.google_compute_image.debian.self_link
    }
  }

  network_interface {
    access_config {}
    subnetwork = google_compute_subnetwork.subnetwork_a.self_link
  }

  service_account {
    email  = google_service_account.vm_service_account.email
    scopes = ["cloud-platform"]
  }

}

resource "google_compute_firewall" "deny_public_access" {
  project        = module.host_project_a.project_id
  name           = "deny-public-access"
  network        = google_compute_network.network_a.self_link
  target_tags    = ["deny-public-access"]
  enable_logging = true

  deny {
    protocol = "tcp"
    ports    = ["80", "22", "443"]
  }

  deny {
    protocol = "icmp"
  }

  source_ranges = ["0.0.0.0/0"]
}
```

This should give you a shared vpc, with a host and service project and a VM with a firewall attached to it.  Once you that, create an additional project, enable the Cloud Monitoring workspace manually.

```tf
module "stackdriver_workspace_project" {
  source  = "terraform-google-modules/project-factory/google"
  version = "~> 8.0"

  name                 = "sd-ws"
  random_project_id    = true
  org_id               = local.organization_id
  billing_account      = local.billing_account_id
  folder_id            = local.sandbox_folder_id
  skip_gcloud_download = true
  activate_apis = [
    "stackdriver.googleapis.com",
    "bigquery.googleapis.com"
  ]
}
```

**Create the policy manual**

1. Create a new alert policy in the project created earlier (`stackdriver_workspace_project`)
2. Resource type = `Subnetwork`, Metric = `Subnet Firewall Hit Count`
3. Configuration: Any time series violates `Increases by 1% for 1 minute` (really low triggers, to make it easier to test this).
4. Hit Add
5. Add a notification channel (I used my email)
6. Hit Save

 **Terraform version** 

1. Use the code I copied above
2. Run `terraform apply`

If you compare the two results in the UI, you should see that there is a difference between the two.  It's difficult to explain why they are so different, given that the `gcloud`-extracts are exactly the same.

To trigger the alert policy, I used a simpel script to spawn off multiple processes that pings the VM:
```shell
#!/bin/bash

for run in {1..10000}; do
  ping ${PUBLIC_IP} -c 1 2>&1 > /dev/null &
done
```

Any thoughts?
