### ISSUE TITLE
google_compute_backend_service doesn't support serverless NEGs

### ISSUE THREAD

**Issue by andyroyle** [hashicorp/terraform-provider-google#6876]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

terraform: 0.12.28
google-beta: 3.32.0

### Affected Resource(s)

* google_compute_backend_service

### Terraform Configuration Files
```
resource "google_compute_backend_service" "backend-service" {
  provider = google-beta

  name            = "my-backend-service

  backend {
      group = "https://www.googleapis.com/compute/beta/projects/my-project/regions/europe-west1/networkEndpointGroups/my-serverless-neg"
  }
}
```

### Expected Behavior

Backend should be created.

### Actual Behavior

```
Error creating BackendService: googleapi: Error 400: Invalid value for field 'resource.backends[0].maxUtilization': '1.0'. Max utilization is not supported for Serverless network endpoint groups., invalid
```

The api doesn't allow specifying `maxUtilization` for a serverless NEG backend, there *is* code for explicitly supporting global NEGs (see [here](https://github.com/terraform-providers/terraform-provider-google-beta/blob/release-3.32.0/google-beta/resource_compute_backend_service.go#L3262-L3265)) but it's specifically looking for `global/networkEndpointGroups` in the string, so the serverless NEGs don't trigger this behaviour.

Since the Serverless NEGs are now in Beta I thought it prudent to open an issue (in case the fix for this is already in the pipeline).

I can easily send a PR to fix this logic so that it also applies to regional NEGs but I'm not sure of the wider implication here and wouldn't want to break any other behaviour.

**Comment by edwardmedia** [comment]
@andyroyle can you see if **google_compute_region_backend_service** works for you? If not, can you post your debug log?

**Comment by kentb** [comment]
@edwardmedia @andyroyle  I believe this is related to this issue: https://github.com/hashicorp/terraform-provider-google/issues/6749 
Looks like the fixed has been merged and ready to be released.

**Comment by kentb** [comment]
I'm able to reproduce the same issue.
I know Serverless NEGs is coming out on the next release.
It'll be good to have this fix come out soon, so we can properly use the Serverless NEGs.

### Terraform Version
terraform: 0.13.0
google-beta: 3.34.0

### Affected Resource(s)
* google_compute_backend_service

### Terraform Configuration Files
```
resource "google_compute_backend_service" "backend-service" {
  provider = google-beta

  name            = "my-backend-service
  backend {
      group = "https://www.googleapis.com/compute/beta/projects/my-project/regions/europe-west1/networkEndpointGroups/my-serverless-neg"
  }
}
```

### Expected Behavior
Backend should be created.

### Actual Behavior
```
Error: Error creating BackendService: googleapi: Error 400: Invalid value for field 'resource.backends[0].maxUtilization': '0.8'. Max utilization is not supported for Serverless network endpoint groups., invalid
```

**Comment by kentb** [comment]
[backend-service-serverless-neg-error.txt](https://github.com/hashicorp/terraform-provider-google/files/5059888/backend-service-serverless-neg-error.txt)
Here's the Debug log from the above run.
Note that I replaced the actual project name w/ the dummy name from above example.

**Comment by edwardmedia** [comment]
@kentb do **google_compute_region_backend_service** work for you?

**Comment by kentb** [comment]
@edwardmedia 
It doesn't work since it requires healthchecks, serverless NEG's also do not have healthchecks.
According to GCP docs, Serverless NEGs only work with Global backend service.
https://cloud.google.com/load-balancing/docs/backend-service

<img width="1959" alt="GlobalBackend-Serverless" src="https://user-images.githubusercontent.com/618315/90036169-8e02f980-dc77-11ea-9eba-6951d7a6a433.png">

**Comment by kentb** [comment]
If it helps, here are the details of a Backend Service I created using gcloud commands, connected to 2 Serverless NEGs in us-east4 and europe-west1. (Names are swapped w/ more generic ones)

```
$gcloud compute backend-services describe my-backend-service

affinityCookieTtlSec: 0
backends:
- balancingMode: UTILIZATION
  capacityScaler: 0.0
  group: https://www.googleapis.com/compute/v1/projects/myproject-123456/regions/us-east4/networkEndpointGroups/my-backend-service-us-east4-serverless-neg
- balancingMode: UTILIZATION
  capacityScaler: 0.0
  group: https://www.googleapis.com/compute/v1/projects/myproject-123456/regions/europe-west1/networkEndpointGroups/my-backend-service-europe-west1-serverless-neg
connectionDraining:
  drainingTimeoutSec: 0
creationTimestamp: '2020-08-07T09:27:40.228-07:00'
description: ''
enableCDN: false
fingerprint: xxx
id: 'xxx'
kind: compute#backendService
loadBalancingScheme: EXTERNAL
logConfig:
  enable: false
name: my-backend-service
port: 80
portName: http
protocol: HTTP
selfLink: https://www.googleapis.com/compute/v1/projects/myproject-123456/global/backendServices/my-backend-service
sessionAffinity: NONE
timeoutSec: 30
```
