### ISSUE TITLE
NEGs and SQL private connections not destroyed

### ISSUE THREAD

**Issue by warden** [hashicorp/terraform-provider-google#7637]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.13.3

### Affected Resource(s)

* google_XXXXX

### Terraform Configuration Files

```tf
provider "google" {
  project     = var.project_id
  region      = var.region
  zone        = var.zone
  version     = ">= 3.43.0"
}

provider "google-beta" {
  project     = var.project_id
  region      = var.region
  zone        = var.zone
  version     = ">= 3.43.0"
}


resource "google_compute_network" "vpc" {
  name                    = "app-vpc"
  auto_create_subnetworks = "false"
}

resource "google_compute_subnetwork" "gke-subnet" {
  name          = "gke-subnet"
  region        = var.region
  network       = google_compute_network.vpc.name
  ip_cidr_range = "10.10.0.0/16"
}

resource "google_container_cluster" "the_cluster" {
  provider            = google-beta
  name                = "gke"
  project             = var.project_id
  # single-zone cluster
  location            = var.zone
  # we need 1.17.6+ to use NEGs
  # https://cloud.google.com/kubernetes-engine/docs/concepts/ingress
  # min_master_version  = data.google_container_engine_versions.default.latest_master_version
  min_master_version = "1.17.12-gke.2502"

  remove_default_node_pool = true
  initial_node_count       = 1

  # Create a VPC-native GKE cluster instead of route-based cluster
  network    = google_compute_network.vpc.name
  subnetwork = google_compute_subnetwork.gke-subnet.name
  networking_mode = "VPC_NATIVE"

  ip_allocation_policy {
    cluster_ipv4_cidr_block = "/20"
    services_ipv4_cidr_block = "/20"
  }

  master_auth {
    username = var.gke_username
    password = var.gke_password

    client_certificate_config {
      issue_client_certificate = false
    }
  }
}


resource "random_id" "db-rand-suffix" {
   byte_length = 4
 }

 resource "google_project_service" "compute-api" {
   project            = data.google_project.project.project_id
   service            = "compute.googleapis.com"
   disable_on_destroy = false
 }

 resource "google_project_service" "service-networking-api" {
   project            = data.google_project.project.project_id
   service            = "servicenetworking.googleapis.com"
   disable_on_destroy = false
 }

 resource "google_compute_global_address" "private-ip-address" {
   provider      = google-beta
   project       = data.google_project.project.project_id

   name          = google_compute_network.vpc.name
   network       = google_compute_network.vpc.name
   prefix_length = 20
   purpose       = "VPC_PEERING"
   address_type  = "INTERNAL"
 }

 resource "google_service_networking_connection" "private_vpc_connection" {
   provider = google-beta
   network                 = google_compute_network.vpc.self_link
   service                 = "servicenetworking.googleapis.com"
   reserved_peering_ranges = [ google_compute_global_address.private-ip-address.name ]
 }

resource "google_sql_database_instance" "pginstance" {
  name   = "db-private-instance3-${random_id.db-rand-suffix.hex}"
  database_version = "POSTGRES_12"
  region = var.region

  depends_on = [ google_service_networking_connection.private_vpc_connection ]

  settings {
    tier = "db-f1-micro"

    backup_configuration {
      enabled = true
    }
    
    ip_configuration {
      ipv4_enabled    = false
      private_network = google_compute_network.vpc.id
    }
  }

}
```

K8S deployment manifest:
```
gcloud container clusters get-credentials gke
kubectl apply -f manifest.yml
```

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: app


---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: web
  template:
    metadata:
      labels:
        tier: web
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: web
          image: nginxdemos/hello:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: API_HOST
              value: "http://api"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: api
  template:
    metadata:
      labels:
        tier: api
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: api
          imagePullPolicy: Always
          image: gcr.io/google-samples/hello-app:2.0
          ports:
            - containerPort: 80
          readinessProbe:
            initialDelaySeconds: 3
            periodSeconds: 3
            httpGet:
              path: /api/status
              port: 80
          env:
            - name: PORT
              value: "80"
            - name: DBHOST
              value: "localhost"
            - name: DBPORT
              value: "5432"
            - name: DBNAME
              value: "appdb"
            - name: DBUSER
              value: "appdbuser"
              # This needs to be rewritten to use secrets
            - name: DBPASS
              value: "appdbpass"


---
apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: web

spec:
  type: ClusterIP
  selector:
    tier: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: api

spec:
  type: ClusterIP
  selector:
    tier: api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: app
  name: app-ingress
spec:
  backend:
    serviceName: web
    servicePort: 80
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: web
          servicePort: 80
      - path: /api/*
        backend:
          serviceName: api
          servicePort: 80
```

### Expected Behavior

Facts:
- the GKE cluster and private SQL instance is provisioned correctly
- for the GKE to connect to SQL, a peering is established

Expected behavior:
- when `terraform destroy` I expect the whole infrastructure to be destroyed

### Actual Behavior

- GKE is destroyed
- SQL instance is destroyed
- VPC cannot be destroyed as there is a "leftover" peering between VPC and SQL private network and because NEGs are present

### Steps to Reproduce

- rollout the infra 
- deploy k8s manifest and wait until NEGs are created and Ingress IP appears on `kubectl --namespace=app describe ingress`
- run `terraform destroy` and observe that:
  - the VPC is still there 
  - the VPC peering is still there
  - in Compute Engine > Network Endpoint Groups are still there

### References

- see remark at https://www.terraform.io/docs/providers/google/r/sql_database_instance.html#private-ip-instance
