### ISSUE TITLE
Add google_compute_instance argument to enable GCP cofidential compute instances

### ISSUE THREAD

**Issue by salrashid123** [hashicorp/terraform-provider-google#7936]
Terraform provider (`v3.49.0`) does not include an argument that would enable a GCE VM to use [Confidential Compute](https://cloud.google.com/compute/confidential-vm/docs/creating-cvm-instance#create_a_new_instance)

the config parameter to enable that is:
```yaml
  "confidentialInstanceConfig": {
    "enableConfidentialCompute": true
  },
```
[API:](https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert#request-body)
```json
  "confidentialInstanceConfig": {
    "enableConfidentialCompute": boolean
  },
```

---

maybe something similar to the `shieldedInstanceConfig` setting
https://github.com/GoogleCloudPlatform/magic-modules/blob/master/products/compute/api.yaml#L6329
