### ISSUE TITLE
Setting kubelet_config to disable cpu_cfs_quota does not seem to work

### ISSUE THREAD

**Issue by sharkymcdongles** [hashicorp/terraform-provider-google#7968]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.29
provider-google-beta v3.50.0

### Affected Resource(s)

```
terraform
resource "google_container_cluster" "cluster" {
  provider         = google-beta
```
```
terraform
resource "google_container_node_pool" "node_pools" {
  provider = google-beta
```
### Terraform Configuration Files

```
terraform
resource "google_container_node_pool" "node_pools" {
  provider = google-beta
  for_each = var.node_pools

  name       = each.key
  project    = google_container_cluster.cluster.project
  location   = google_container_cluster.cluster.location
  cluster    = google_container_cluster.cluster.name
  node_count = each.value.min_node_count

  version = local.kubernetes_version

  autoscaling {
    min_node_count = each.value.min_node_count
    max_node_count = each.value.max_node_count
  }

  management {
    auto_upgrade = false
    auto_repair  = true
  }

  upgrade_settings {
    max_surge       = 3
    max_unavailable = 0
  }

  node_config {
    preemptible  = each.value.preemptible
    machine_type = each.value.machine_type
    disk_type    = each.value.disk_type
    disk_size_gb = each.value.disk_size_gb
    image_type   = each.value.image_type
    labels       = each.value.labels
    tags         = each.value.tags

    kubelet_config {
      cpu_manager_policy   = "none"
      cpu_cfs_quota        = false
    }

    linux_node_config {
      sysctls = {
        "net.core.netdev_max_backlog" = "4096"
        "net.core.somaxconn"          = "4096"
        "net.core.rmem_max"           = "16777216"
        "net.core.wmem_max"           = "16777216"
        "net.ipv4.tcp_tw_reuse"       = "1"
        "net.ipv4.tcp_rmem"           = "4096 87380 16777216"
        "net.ipv4.tcp_wmem"           = "4096 65536 16777216"
      }
    }

    shielded_instance_config {
      enable_secure_boot = true
    }
  }

  depends_on = [
    google_container_cluster.cluster]
}
```

### Expected Behavior

Node pools are provisioned with kubelet_config settings respected.

### Actual Behavior

kubelet_config settings aren't set and checking in GUI or via gcloud shows nothing:

❯ gcloud --project CENSORED compute instances describe --zone europe-west2-b INSTANCE| grep -i -A10 cpu

```
cpuPlatform: Intel Broadwell
creationTimestamp: '2020-12-08T07:29:23.972-08:00'
deletionProtection: false
disks:
- autoDelete: true
  boot: true
  deviceName: persistent-disk-0
  diskSizeGb: '128'
  guestOsFeatures:
  - type: UEFI_COMPATIBLE
  - type: SECURE_BOOT
--
      cpuManagerPolicy: none
      enableDebuggingHandlers: true
      evictionHard:
        memory.available: 100Mi
        nodefs.available: 10%
        nodefs.inodesFree: 5%
        pid.available: 10%
      featureGates:
        DynamicKubeletConfig: false
        RotateKubeletServerCertificate: true
      kind: KubeletConfiguration
--
        cpu: 150m
        ephemeral-storage: 50Gi
        memory: 11019Mi
      readOnlyPort: 10255
      serverTLSBootstrap: true
      staticPodPath: /etc/kubernetes/manifests
  - key: kubeconfig
    value: |
      apiVersion: v1
      kind: Config
      clusters:
--
      AUTOSCALER_ENV_VARS: kube_reserved=cpu=150m,memory=11019Mi,ephemeral-storage=50Gi;node_labels=addon.gke.io/node-local-dns-ds-ready=true,agentpool=predynamic,cloud.google.com/gke-nodepool=predynamic,cloud.google.com/gke-os-distribution=cos,cloud.google.com/machine-family=n1,node.kubernetes.io/masq-agent-ds-ready=true,projectcalico.org/ds-ready=true;os=linux
      CA_CERT: 
      CLUSTER_IP_RANGE: 10.79.0.0/18
      CLUSTER_NAME: CLUSTER
      CNI_HASH: 
      CNI_SHA1: dcbeba8d6be7a49e399bda6b8b638d312eace876
      CNI_STORAGE_PATH: https://storage.googleapis.com/gke-release/cni-plugins/v0.8.5-gke.1
      CNI_STORAGE_URL_BASE: https://storage.googleapis.com/gke-release/cni-plugins
      CNI_TAR_PREFIX: cni-plugins-linux-amd64-
      CNI_VERSION: v0.8.5-gke.1
      CONTAINER_RUNTIME: containerd
```

### Steps to Reproduce

Set kubelet_config per the documentation for the nodepools with the beta provider and apply.

### Important Factoids

N/A

### References

Per the documentation and these issue tickets this should work:

https://github.com/hashicorp/terraform-provider-google/pull/7060
https://github.com/hashicorp/terraform-provider-google/issues/6773
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#kubelet_config

**Comment by edwardmedia** [comment]
@sharkymcdongles i tested it seems fine with me. Below is what I got. 

```
config:
  diskSizeGb: 100
  diskType: pd-standard
  imageType: COS
  kubeletConfig:
    cpuManagerPolicy: none
  machineType: e2-medium
```

Not sure why you checked by running `gcloud compute instances...`. Mine is `gcloud beta container node-pools describe....` Do you want to try?

**Comment by sharkymcdongles** [comment]
@edwardmedia I tried the command you suggested and here is what I get back:

gcloud beta container node-pools describe --project MY_PROJECT --cluster MY_CLUSTER --region europe-west2 MY_NODEPOOL

```
autoscaling:
  enabled: true
  maxNodeCount: 5
  minNodeCount: 1
config:
  diskSizeGb: 128
  diskType: pd-standard
  imageType: COS_CONTAINERD
  kubeletConfig:
    cpuManagerPolicy: none
  labels:
    agentpool: prebatch
  linuxNodeConfig:
    sysctls:
      net.core.netdev_max_backlog: '4096'
      net.core.rmem_max: '16777216'
      net.core.somaxconn: '4096'
      net.core.wmem_max: '16777216'
      net.ipv4.tcp_rmem: 4096 87380 16777216
      net.ipv4.tcp_tw_reuse: '1'
      net.ipv4.tcp_wmem: 4096 65536 16777216
  machineType: n1-highmem-16
  metadata:
    disable-legacy-endpoints: 'true'
  oauthScopes:
  - https://www.googleapis.com/auth/logging.write
  - https://www.googleapis.com/auth/monitoring
  preemptible: true
  serviceAccount: default
  shieldedInstanceConfig:
    enableIntegrityMonitoring: true
    enableSecureBoot: true
  tags:
  - private
  - private-pool
initialNodeCount: 1
instanceGroupUrls: (censored)
locations:
- europe-west2-b
management:
  autoRepair: true
maxPodsConstraint:
  maxPodsPerNode: '110'
name: prebatch
podIpv4CidrSize: 24
status: RUNNING
upgradeSettings:
  maxSurge: 3
version: 1.17.13-gke.2001

```

I'd expect to see this under kubelet config because cpuCFSQuota is true by default:

```
  kubeletConfig:
    cpuManagerPolicy: none
    cpuCFSQuota: false
```

![image](https://user-images.githubusercontent.com/29139537/101521398-183d3f00-3986-11eb-985d-b92a62c35aa4.png)

**Comment by edwardmedia** [comment]
@sharkymcdongles I can't explain you can't see it. You may post the debug log for `terraform apply`, and I can take a look.

**Comment by sharkymcdongles** [comment]
I dont see it in what you pasted me from your end either though. All I see
is cpuManagerPolicy nothing cos quota related. Can you see cfs quota as
false in your output for nodepools describe?

I am afk now, but I can add logs tomorrow. When I check the plan and state
I do see it set, but I don't see it anywhere in gcloud cli nor the gui.

**Comment by edwardmedia** [comment]
@sharkymcdongles I see what the problem is. No log needed. Thanks

**Comment by edwardmedia** [comment]
@sharkymcdongles this appears not an issue. You may see _cpuCFSQuota is **false** by default_ from the screenshot you posted above

```
I'd expect to see this under kubelet config because cpuCFSQuota is true by default:
```

**Comment by sharkymcdongles** [comment]
@edwardmedia I saw your PR. It seems you are saying the cfsquota cannot be set if the cpu manager is set is that correct? I ran a test with the cli tool to see what happens:

`gcloud beta container node-pools create cfsquotatest --image-type=COS_CONTAINERD --machine-type=e2-standard-2 --node-locations=europe-west4-b --preemptible --shielded-secure-boot --system-config-from-file=./kubelet_test.yaml --region=europe-west4 --cluster testcluster`

My kubelet_test.yaml is the following:

```
kubeletConfig:
  cpuManagerPolicy: none
  cpuCFSQuota: false
linuxConfig:
  sysctl:
    net.core.somaxconn: '2048'
    net.ipv4.tcp_rmem: '4096 87380 6291456'
```

The following command:
`gcloud beta container node-pools describe cfsquotatest --cluster testcluster --region europe-west4`

Returns this:
```
config:
  diskSizeGb: 100
  diskType: pd-standard
  imageType: COS_CONTAINERD
  kubeletConfig:
    cpuCfsQuota: false
    cpuManagerPolicy: none
  linuxNodeConfig:
    sysctls:
      net.core.somaxconn: '2048'
      net.ipv4.tcp_rmem: 4096 87380 6291456
  machineType: e2-standard-2
  metadata:
```

So it does seem you can set none and cfsquota false, and it is applied from GKE. I will try removing the non and reapplying my terraform automation though to see if it works as expected.
