### ISSUE TITLE
Permadiff in google_binary_authorization_attestor

### ISSUE THREAD

**Issue by bastian-hafer-db** [hashicorp/terraform-provider-google#8511]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.13.0

### Affected Resource(s)

- google_binary_authorization_attestor
- google_kms_crypto_key_version data source

Used provider version 3.57

### Terraform Configuration Files

```tf
data "google_kms_crypto_key_version" "pipeline_latest" {
  crypto_key = var.attestor_crypto_key
}

resource "google_container_analysis_note" "pipeline" {
  # ...
}

resource "google_binary_authorization_attestor" "pipeline" {
  name    = var.attestation_target
  project = var.project
  attestation_authority_note {
    note_reference = google_container_analysis_note.pipeline.name
    public_keys {
      id = data.google_kms_crypto_key_version.pipeline_latest.id
      pkix_public_key {
        public_key_pem      = data.google_kms_crypto_key_version.pipeline_latest.public_key[0].pem
       # Permadiff occurs here:
        signature_algorithm = data.google_kms_crypto_key_version.pipeline_latest.public_key[0].algorithm 
      }
    }
  }
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

No permadiff

### Actual Behavior

Permadiff: 

```
  # google_binary_authorization_attestor.pipeline will be updated in-place
  ~ resource "google_binary_authorization_attestor" "pipeline" {
        id      = "..."
        name    = "pipeline"
        project = "..."

      ~ attestation_authority_note {
            delegation_service_account_email = "..."
            note_reference                   = "..."

          ~ public_keys {
                id = "..."

              ~ pkix_public_key {
                    public_key_pem      = <<~EOT
                        -----BEGIN PUBLIC KEY-----
                        # ...
                        -----END PUBLIC KEY-----
                    EOT
                  ~ signature_algorithm = "ECDSA_P256_SHA256" -> "EC_SIGN_P256_SHA256"
                }
            }
        }
    }
```

### Steps to Reproduce

1. Get algorithm `EC_SIGN_P256_SHA256` from data source 
2. Create attestor with algorithm
3. Repeatedly `terraform apply`
4. Attestor resource normalizes the algorithm to `ECDSA_P256_SHA256`. This causes a permadiff.

### Important Factoids

N/A

### References

N/A

**Comment by venkykuberan** [comment]
Probably API is returning `ECDSA_P256_SHA256` in the response during the resource creation. Can you please attach your debug log here, want to see the request/response to understand what's going on ?

**Comment by josef-brandl-db** [comment]
Hi, Josef here. I'm a team colleague of @bastian-hafer-db. 

> Can you please attach your debug log here, want to see the request/response to understand what's going on ?

@venkykuberan Yes this is what is happening. The attestor API normalizes the crypto algorithm to `ECDSA_P256_SHA256`:

```
~ ❯ gcloud container binauthz attestors describe pipeline
name: projects/***/attestors/pipeline
updateTime: '2021-02-23T08:56:31.843536Z'
userOwnedGrafeasNote:
  delegationServiceAccountEmail: service-***@gcp-sa-binaryauthorization.iam.gserviceaccount.com
  noteReference: projects/***/notes/pipeline
  publicKeys:
  - id: //cloudkms.googleapis.com/v1/projects/***/locations/europe-west3/keyRings/***/cryptoKeys/pipeline/cryptoKeyVersions/1
    pkixPublicKey:
      publicKeyPem: |
        -----BEGIN PUBLIC KEY-----
        ***
        -----END PUBLIC KEY-----
      signatureAlgorithm: ECDSA_P256_SHA256 # <======= see value here
```

So, the returned value never matches the `EC_SIGN_P256_SHA256 ` value that the data source gets from the KMS API:

```
~ ❯ gcloud kms keys describe projects/***/locations/europe-west3/keyRings/***/cryptoKeys/pipeline/cryptoKeyVersions/1
algorithm: EC_SIGN_P256_SHA256 # <======= see value here
attestation:
  certChains: ***
  content: ***
  format: CAVIUM_V2_COMPRESSED
createTime: '2021-02-12T15:25:18.557402714Z'
generateTime: '2021-02-12T15:25:18.682503561Z'
name: projects/***/locations/europe-west3/keyRings/***/cryptoKeys/pipeline/cryptoKeyVersions/1
protectionLevel: HSM
state: ENABLED
```

In isolation, without a data source, there wouldn't be a diff. But in combination with the data source there is. The provider could suppress this diff. IMO chaining a KMS crypto key version data source and an attestor resource together is a common use case. It is also shown in the docs for the attestor resource as a code example: [Example Usage - Binary Authorization Attestor Kms](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/binary_authorization_attestor#example-usage---binary-authorization-attestor-kms)
