### ISSUE TITLE
Traffic tags and URLs removed from Cloud Run traffic definition

### ISSUE THREAD

**Issue by jakubmiarka** [hashicorp/terraform-provider-google#8654]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When any change to Cloud Run resource (`google_cloud_run_service`) is triggered, the `apply` removes existing values from the Traffic property of the service definition.

In our set-up we use Terraform to manage the Cloud Run deployment (env vars, IAM, resources ...) but we use Cloud Build to deploy new revisions. For these revisions [we assign a traffic tag](https://cloud.google.com/sdk/gcloud/reference/beta/run/services/update#--tag) using `gcloud` CLI. The YAML definition after a few deployments looks like:
```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
    ...
spec:
  template:
    metadata:
        ...
    spec:
      ...
  traffic:
  - revisionName: api-00001-kaz
    tag: dev-46351b6
  - revisionName: api-00002-goq
    tag: dev-7791b74
status:
  ...
  traffic:
  - revisionName: api-00001-kaz
    tag: dev-46351b6
    url: https://dev-46351b6---api-abcd-nw.a.run.app
  - revisionName: api-00002-goq
    tag: dev-7791b74
    url: https://dev-7791b74---api-abcd-nw.a.run.app
  url: https://api-abcd-nw.a.run.app
  address:
    url: https://api-abcd-nw.a.run.app
```

When terraform runs on an unrelated change (such as a change in env var), the plan shows only the env var change. However, when `apply` runs it removes all the `tag` and `url` properties, so the `traffic` then looks like:
```yaml
...
traffic:
  - revisionName: api-00001-kaz
  - revisionName: api-00002-goq
...
```
and we lose our traffic tags and ability to hit/test specific revisions. 

From a quick look, I believe the root cause is a mismatch in the schema of the traffic object. [Google docs](https://cloud.google.com/run/docs/reference/rest/v1/TrafficTarget) define it as
```json
{
  "configurationName": string,
  "revisionName": string,
  "percent": integer,
  "tag": string,
  "latestRevision": boolean,
  "url": string
}
```
However, the provider seems to only have:
```json
{
  "revisionName": string,
  "percent": integer,
  "latestRevision": boolean
}
```
as per [the code here](https://github.com/hashicorp/terraform-provider-google/blob/20c4bfce221cd8a081bf74a8850095830eb3c759/google/resource_cloud_run_service.go#L495-L514). And I suspect when [this function runs](https://github.com/hashicorp/terraform-provider-google/blob/20c4bfce221cd8a081bf74a8850095830eb3c759/google/resource_cloud_run_service.go#L1006) it strips out everything except the 3 known properties:
https://github.com/hashicorp/terraform-provider-google/blob/20c4bfce221cd8a081bf74a8850095830eb3c759/google/resource_cloud_run_service.go#L1018-L1022

Can the TF's schema be updated to match the GCP's one? Any suggested workarounds in the meantime?

### New or Affected Resource(s)

* google_cloud_run_service
