### ISSUE TITLE
google_compute_managed_ssl_certificate does not support namespace prefix

### ISSUE THREAD

**Issue by hazcod** [hashicorp/terraform-provider-google#9080]
### Terraform Version

Terraform v0.15.1
on darwin_arm64

### Affected Resource(s)

google_compute_managed_ssl_certificate

### Terraform Configuration Files

```tf
resource "google_compute_managed_ssl_certificate" "gke_ingress_cert" {
    name = "gke-ingress-cert"

    managed {
        domains = [
            "foo.com"
        ]
    }
}
```

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: "ingress"
  namespace: "dev-web"
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "{{ .Values.externalIPName }}"
    networking.gke.io/managed-certificates: "gke-ingress-cert"
```

### Expected

Be able to automatically create an ingress for cert `gke-ingress-cert`.

### Outcome

Console returns `ManagedCertificate dev-web:gke-ingress-cert missing`.
If I try to set `dev-web:gke-ingress-cert` in the `name` attribute in terraform, it complains I cannot use `:`.
