### ISSUE TITLE
google_compute_instance_template.advanced_machine_features erroneously marked as computed

### ISSUE THREAD

**Issue by karlkfi** [hashicorp/terraform-provider-google#9436]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

terraform-provider-google v3.73.0

This version JUST added the `advanced_machine_features` field. So no other versions are affected yet.

### Affected Resource(s)

* google_compute_instance_template

### Terraform Configuration Files

Example used to test KCC (does not specify AdvancedMachineFeatures, because it was only just added) :

```
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstanceTemplate
metadata:
  name: computeinstancetemplate-${uniqueId}
  labels:
    label-one: "value-one"
spec:
  description: a basic instance template example
  machineType: n1-standard-1
  region: us-central1
  metadata:
    - key: foo
      value: bar
    - key: bar
      value: baz
  disk:
    - sourceDiskRef:
        name: computedisk-${uniqueId}
      autoDelete: false
      boot: true
    - sourceImageRef:
        name: computeimage-${uniqueId}
      autoDelete: true
      boot: false
  networkInterface:
    - networkRef:
        name: computenetwork-${uniqueId}
      subnetworkRef:
        name: computesubnetwork-${uniqueId}
```

### Error Output

This error is from the Config Connector integration tests after pulling in the new terraform-provider-google v3.73.0 code as dependency.

> samples_test.go:297: timed out waiting for ready on ComputeInstanceTemplate with name 'srxlguaxsm', final status.conditions[0] status 'False' and reason 'UpdateFailed': Update call failed: cannot make changes to immutable field(s): [advancedMachineFeatures.#]

However, no changes were made to the advancedMachineFeatures field, because it's not even being specified by the existing integration tests (new field).

### Expected Behavior

The test should pass, because the advancedMachineFeatures field is not being specified by the client nor changed.

### Actual Behavior

The test fails, with the error: `cannot make changes to immutable field(s): [advancedMachineFeatures.#]`.

Terraform Provider Google would probably always trigger an unnecessary re-create as long as `advanced_machine_features` is empty and an update was performed. 

**TODO**: Validate the actual error behavior when using TF without KCC.

### Probable Root Cause

The `advanced_machine_features` field is marked as `Computed: true` and `ForceNew: true`. So when calculating the diff, if the new value is empty, the diff sets `RequiresNew: true`, which triggers a `ImmutableFieldsMutationError` error from Config Connector, even if nothing changed.

https://github.com/hashicorp/terraform-plugin-sdk/blob/main/helper/schema/schema.go#L394

### References

* https://github.com/hashicorp/terraform-provider-google/issues/9251
* https://github.com/hashicorp/terraform-provider-google/pull/9363
* https://github.com/hashicorp/terraform-provider-google/releases/tag/v3.73.0
