### ISSUE TITLE
ExactlyOneOf doesn't work with mmv1 fields that have their names overriden in terraform.yaml

### ISSUE THREAD

**Issue by upodroid** [hashicorp/terraform-provider-google#9689]
Technical Debt

As part of https://github.com/GoogleCloudPlatform/magic-modules/pull/4993 the following mmv1 config doesn't work.

```
# api.yaml
      - !ruby/object:Api::Type::Integer
        name: 'nodeCount'
        description: |
          The number of nodes allocated to this instance. At most one of either node_count or processing_units can be present in terraforn. 
        exactly_one_of:
          - num_nodes
          - processing_units
      - !ruby/object:Api::Type::Integer
        name: 'processingUnits'
        description: |
          The number of processing units allocated to this instance. At most one of processing_units 
          or node_count can be present in terraform. 
        exactly_one_of:
          - num_nodes
          - processing_units
```

```
# terraform.yaml
      nodeCount: !ruby/object:Overrides::Terraform::PropertyOverride
        name: num_nodes
        default_from_api: true
      processingUnits: !ruby/object:Overrides::Terraform::PropertyOverride
        default_from_api: true
```

Generates the following schema:

```
			"num_nodes": {
				Type:         schema.TypeInt,
				Optional:     true,
				Description:  `The number of nodes allocated to this instance. At most one of either node_count or processing_units can be present in terraforn.`,
				ExactlyOneOf: []string{"processing_units"},
			},
			"processing_units": {
				Type:     schema.TypeInt,
				Optional: true,
				Description: `The number of processing units allocated to this instance. At most one of processing_units 
or node_count can be present in terraform.`,
				ExactlyOneOf: []string{"processing_units"},
			},
```

This bug will block this issue from being resolved #9685
